### ISSUE TITLE
No picture in Traktv

### ISSUE THREAD

**Issue by xmenxmen** [SickRage/SickRage#3077] opened 2017-02-03 14:12 UTC
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```
Synology DSM 6.xx

Branch: master
Commit: 7e6e0575542c3f3e5476663532b1357f3ae1e902
Version: v2017.02.2-1
Database Version: 44.0

Hi.
Is it just me,or are there no picture in add shows in Traktv?
Thanks for very nice program.

**Comment by SickRage2** [comment] 2017-02-03 14:12
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment] 2017-02-04 05:02
Nope, trakt stopped supplying show posters, just need some time to fix it or someone to make a PR. Very low priority

**Comment by h3llrais3r** [comment] 2017-03-07 20:24
What will we do here? Just remove the posters from the view? Or get them from somewhere else?

**Comment by miigotu** [comment] 2017-03-07 20:31
they will be cached into SR backend from thetvdb with an ajax call and returned

**Comment by sharkykh** [comment] 2017-03-07 20:32
I tried to do that. It's quite slow to pull a poster link for each of the shows in the Trakt lists.
I looked but couldn't find a way to bulk-search with the tvdb-api, like Trakt does...

I've seen a fix that utilizes caching for the posters, so the first download will take like a minute or so for 100 shows, then you'll be able to display them from cache (much like the tvshow posters right now)

BUT I don't know how to do that :disappointed:

**Comment by h3llrais3r** [comment] 2017-03-07 20:35
Will see if I can do something about it.
For now, I'll close this one and mark it as duplicate of https://github.com/SickRage/SickRage/issues/2961

**Closed by h3llrais3r** 2017-03-07 20:35 UTC
