### ISSUE TITLE
Post processing re-adds deleted episodes

### ISSUE THREAD

**Issue by rasmusbe** [SickRage/SickRage#3200] opened 2017-02-22 19:24 UTC
Branch/Commit: master / v2017.02.20-1
OS: Win10
What you did:
1. Activate post processing and unrar.
2. Download rared episode
3. Post processor unrars and moves video file
4. Delete video file, keep rars in the other folder
5. Rescan files, episode gets marked as archived (according to the setting)
6. Wait for the automatic post processing job. 
7. Episode is unrared again 😞 

What you expected:
The post processing job should not unrar archived episodes.

Logs:
```
2017-02-22 20:20:13 INFO POSTPROCESSOR-AUTO :: Auto post processing task for D:\Downloads\sickrage completed
2017-02-22 20:20:13 INFO POSTPROCESSOR-AUTO :: Successfully processed
2017-02-22 20:20:13 INFO POSTPROCESSOR-AUTO :: Successfully processed
2017-02-22 20:20:13 INFO POSTPROCESSOR-AUTO :: Deleting folder (if it's empty): D:\Downloads\sickrage\show.episode\show.episode
2017-02-22 20:20:13 INFO POSTPROCESSOR-AUTO :: Processing succeeded for D:\Downloads\sickrage\show.episode\show.episode\video.mkv
2017-02-22 20:20:12 INFO POSTPROCESSOR-AUTO :: Using nzb_name for release name.
2017-02-22 20:20:12 INFO POSTPROCESSOR-AUTO :: Process method is 'move' and src and destination are on the same device, skipping free space check
2017-02-22 20:20:12 INFO POSTPROCESSOR-AUTO :: Processing D:\Downloads\sickrage\show.episode\show.episode\video.mkv (show.episode)
2017-02-22 20:20:08 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: D:\Downloads\sickrage
2017-02-22 20:20:03 INFO POSTPROCESSOR :: Auto post processing task for D:\Downloads\sickrage was added to the queue
```

**Comment by SickRage2** [comment] 2017-02-22 19:24
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sharkykh** [comment] 2017-02-22 19:50
I was doing some work on that section a few hours ago.
Let me check...

**Comment by sharkykh** [comment] 2017-02-22 20:35
Oops. just read it again.

> What you expected:
The post processing job should not unrar archived episodes.

I thought about something else.

In my mind - this is not a bug.
You deleted the episode, re-scanned the files. SickRage _**no longer has**_ a record of that episode being downloaded or that you had it. It was removed from the database.
So when auto-processing runs again it finds a new download - _**new to SickRage, that is**_

'Archived' means you have it stored somewhere other than (one of) your root directories of SickRage.

**Comment by rasmusbe** [comment] 2017-02-22 20:41
Thank you for your answer, but SickRage has an record of that episode being archived, should it really handle it as a new download?

If I change the settings for deleted episodes to be set to skipped, will that work or will it still consider it as a new download?

**Comment by rasmusbe** [comment] 2017-02-22 21:21
Tried with ignored, still getting re-added.

**Comment by sharkykh** [comment] 2017-02-22 21:34
Episode Status is not the record I was talking about.
The record is the path to the video file linked to that episode, and the release name of that file.
If it's set to nothing (empty) in the database, which is what you did by deleting the file and re-scanning the show files.
Post-processing checks against the database record,
if it's empty, SickRage assumes that you don't have that episode.
and that you just downloaded it by your self (not using SickRage) so it adds it.

I don't understand why you would download something just to remove it.
Also, if you don't want SickRage to pick an episode up in the first place,
don't put it in the download dir that auto-post-processing checks...

**Comment by miigotu** [comment] 2017-02-23 14:48
Fixed in develop. If they have status set to "Archived (Blah)" they wont be extracted.  Will be in master by the weekend.

**Closed by miigotu** 2017-02-23 14:48 UTC

**Comment by rasmusbe** [comment] 2017-02-23 15:01
Thank you @miigotu!

@sharkykh the reason I had the problem is when I deleted a already seen episode that I wanted to continue to seed.

**Comment by miigotu** [comment] 2017-02-23 15:14
Rar'd releases are rarely torrents, they are usually NZB files. Nzb's don't get seeded.

Anyways, please test the develop branch and make sure it fixed your issue.

**Comment by sharkykh** [comment] 2017-02-23 15:20
Rarely is almost exclusively private trackers

**Comment by miigotu** [comment] 2017-02-23 15:25
Even private trackers, rar'd releases are usually against the rules.

**Comment by rasmusbe** [comment] 2017-02-23 15:38
@miigotu develop branch worked fine! great work, thanks!

and the episode I had the problems with was from a private tracker who unfortunately allows rared releases 😞
