### ISSUE TITLE
Search providers page errors with 'TypeError: tuple indices must be integers, not unicode'

### ISSUE THREAD

**Issue by sammcj** [SickRage/SickRage#4721] opened 2018-05-21 08:29 UTC
Branch/Commit: v2018.05.11-1-1-g5a9a634
OS: CentOS 7.5
Browser: Firefox 61
What you did: Clicked 'Search Providers'
What happened: 
```
File /opt/SickRage/gui/slick/views/config_providers.mako:183, in render_pages:
${('', 'checked="checked"')[curNewznabProvider.enable_daily]}
TypeError: tuple indices must be integers, not unicode
```
What you expected: To see the search providers and their settings
Logs: nothing in the log file relating to this at all even with debug logging enabled, the only error is via the browser.

I would have expected some better output about this error, e.g. if it's something in the database causing the issue, where in the database it is.

```sql
sqlite> select * from db_version;
44|0
```

The config file is already ascii with no unicode characters:

```
# iconv --from-code UTF-8 --to-code US-ASCII -c config.ini > config.ascii
# diff config.ini config.ascii
```

**Comment by Ackman999** [comment] 2018-06-01 11:09
Any idea what is causing this?

**Comment by totev** [comment] 2018-06-04 17:35
I am also experiencing this one :(

**Comment by SudoHenk** [comment] 2018-06-04 17:58
Temp fix:

cd /opt/sickrage/ (or different in your setup)
nano -c /gui/slick/views/config_providers.mako

Edit line 183:
`${('', 'checked="checked"')[curNewznabProvider.enable_daily]}` to `${('', 'checked="checked"')[int(curNewznabProvider.enable_daily)]}`

And edit line 247:
`id="${curNewznabProvider.get_id("_search_fallback")}" ${('', 'checked="checked"')[curNewznabProvider.search_fallback]}/>` to `id="${curNewznabProvider.get_id("_search_fallback")}" ${('', 'checked="checked"')[int(curNewznabProvider.search_fallback)]}/>`

Save (Ctrl+x, press y and enter) and reload page.

**Comment by totev** [comment] 2018-06-04 18:15
I can confirm that the patch @SudoHenk suggested is working.

**Comment by Ackman999** [comment] 2018-06-04 18:49
This worked for me also, Thank you @SudoHenk.

**Comment by danastyone** [comment] 2018-06-28 21:47
SudoHenk - Thanks a lot 
The other day I went to my search provider screen and I saw this message. 
So I looked it up and found this.
I'm running this on a DROBO5N , I just opened with notepad++ on my windows machine and edited the file then saved it refreshed the page and it worked :)

Thanks :) again A+

**Comment by ravensorb** [comment] 2018-07-08 19:55
Any ideas when the patch will be applied to the main branch?

**Comment by sammcj** [comment] 2018-07-09 03:08
Really keen for this to work any, any ETA @SickRage ?

**Comment by ravensorb** [comment] 2018-07-19 01:40
Looks like this still wasn't fixed in the latest version?

**Comment by sammcj** [comment] 2018-07-19 06:08
Yeah it’s broken again for me now too.

--
Sam McLeod

**Closed** 2018-07-19 06:20 UTC

**Comment by Memphiisto** [comment] 2018-08-21 15:33
Hey there guys!
@SudoHenk 

I have the exact same issue on Docker AND on Synology... but i cant seem to find a config_providers.mako...

Can anyone help me?
im in /volume1/@appstore/sickrage
and in here i only find 
app
build
env
shar
var

but no gui or slick or anything like that
even the search function didnt help...

pls help me
THANKS!

**Comment by SudoHenk** [comment] 2018-08-21 19:36
Open your `config.ini` and make sure there are no spaces in `curNewznabProvider.enable_daily` and `curNewznabProvider.search_fallback`. Not sure where it's located on your system, but you can check with this on normal linux systems:

```
updatedb
locate config.ini
```
This should list your sickrage config.ini and then you can edit with e.g. `vi` or `nano`.

**Comment by Memphiisto** [comment] 2018-08-22 13:11
@SudoHenk 
Thanks!
I finally understand how it works... but well sadly there still are some problems...

After comparing the original .ini file with the modified .ini file i found that the problem where not the search_fallback or enable_daily.. but some other option further down...

so i replaced it with the original ini file and it started again...
but as soon as i change anything in the settings an press save.. the next time it wont start again...

I want to set my Privoxy as Proxy but i cant because everytime i save everything crashes again....

any suggestions?
Thanks!

**Comment by miigotu** [comment] 2018-09-12 23:34
Likely you have a special/unicode character in the password for the proxy? That may still be unsupported, try an ascii only username/password
