### ISSUE TITLE
New directory not created, but should be

### ISSUE THREAD

**Issue by pven** [SickRage/SickRage#1802] opened 2016-05-18 13:27 UTC
Branch/Commit: master / b790df702cf1ef84ee64b591f40ce6fae86976dc
OS: Synology
What you did: post-process my download-folder
What happened: new directory is not created
What you expected: new directory should be created. When I create the directory by hand, the manual postprocessing is working as expected. The option 'Create missing show directories' is checked.

Logs:
```
2016-05-18 14:43:50 ERROR    Thread-100 :: [b790df7] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 2291, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/processTV.py", line 290, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/processTV.py", line 560, in process_media
    result.result = processor.process()
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/postProcessor.py", line 1027, in process
    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method):  # pylint: disable=protected-access
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/helpers.py", line 1578, in verify_freespace
    if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest).st_dev:  # pylint: disable=no-member
  File "/volume1/@appstore/sickrage/var/SickRage/sickrage/helper/encoding.py", line 40, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
OSError: [Errno 2] No such file or directory: '/volume1/media/TV/The Last Man on Earth'
Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 2291, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/processTV.py", line 290, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/processTV.py", line 560, in process_media
    result.result = processor.process()
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/postProcessor.py", line 1027, in process
    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method):  # pylint: disable=protected-access
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/helpers.py", line 1578, in verify_freespace
    if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest).st_dev:  # pylint: disable=no-member
  File "/volume1/@appstore/sickrage/var/SickRage/sickrage/helper/encoding.py", line 40, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
OSError: [Errno 2] No such file or directory: '/volume1/media/TV/The Last Man on Earth'
2016-05-18 14:43:50 ERROR    Uncaught exception POST /home/postprocess/processEpisode (192.168.1.135)
HTTPServerRequest(protocol='http', host='diskstation:8899', method='POST', uri='/home/postprocess/processEpisode', version='HTTP/1.0', remote_ip='192.168.1.135', headers={'Ori
Traceback (most recent call last):
  File "/usr/local/sickrage/var/SickRage/lib/tornado/web.py", line 1415, in _execute
    result = yield result
  File "/usr/local/sickrage/var/SickRage/lib/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/sickrage/var/SickRage/lib/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/sickrage/var/SickRage/lib/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 254, in get
    results = yield self.async_call(method)
  File "/usr/local/sickrage/var/SickRage/lib/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/sickrage/var/SickRage/lib/concurrent/futures/_base.py", line 400, in result
    return self.__get_result()
  File "/usr/local/sickrage/var/SickRage/lib/concurrent/futures/_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "/usr/local/sickrage/var/SickRage/lib/concurrent/futures/_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/usr/local/sickrage/var/SickRage/lib/concurrent/futures/thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 2291, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/processTV.py", line 290, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/processTV.py", line 560, in process_media
    result.result = processor.process()
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/postProcessor.py", line 1027, in process
    if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method):  # pylint: disable=protected-access
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/helpers.py", line 1578, in verify_freespace
    if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest).st_dev:  # pylint: disable=no-member
  File "/volume1/@appstore/sickrage/var/SickRage/sickrage/helper/encoding.py", line 40, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
OSError: [Errno 2] No such file or directory: '/volume1/media/TV/The Last Man on Earth'
```

**Comment by SickRage2** [comment] 2016-05-18 13:27
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by pven** [comment] 2016-05-19 05:16
I think there is enough information in my initial message :)

**Comment by sferra** [comment] 2016-05-20 22:28
possibly a duplicate of #1790?

**Closed** 2016-05-20 23:52 UTC
