### ISSUE TITLE
Unable to use Sickrage behind a HTTPS to HTTP reverse proxy

### ISSUE THREAD

**Issue by Ripolin** [SickRage/SickRage#3959] opened 2017-08-07 02:36 UTC
Branch: develop
Commit: 434df4ca1faeb7f18f352928a9ad37eb3106cad3

Since commit a1feed4ea019387b31df49dfb0e04f329c4ee4b3, instead of generating relative paths for contents, Sickrage generates static ones.

But when SickRage application is installed behind a https to http reverse proxy, it always generates http paths for static contents in html while requests are send using https. Finally the generated html have http links which are blocked by browsers because contents must be served over https.

https://github.com/SickRage/SickRage/blob/a1feed4ea019387b31df49dfb0e04f329c4ee4b3/sickbeard/webserve.py#L172

The `include_host` var could it be parameterized to reuse relative paths ?

Why to not used relative paths anymore ?

**Comment by OmgImAlexis** [comment] 2017-08-07 03:37
Do you have the reverse proxy setting enabled in [Sickrage's config](https://github.com/SickRage/SickRage/wiki/Settings-explained#user-interface-options-for-visual-appearance)?

![screen shot 2017-08-07 at 1 07 27 pm](https://user-images.githubusercontent.com/6525926/29011346-6c4f8fb6-7b71-11e7-97ce-3c6fb2dd6ebe.png)

**Comment by Ripolin** [comment] 2017-08-07 11:57
Yes and it's works fine for the master branch but no more for the develop one.

**Comment by OmgImAlexis** [comment] 2017-08-07 12:12
@miigotu any chance this is caused by the `static_url` changes?

**Comment by miigotu** [comment] 2017-08-07 12:13
possibly, I linked a possible fix to sharky in the pr, lets see if thats possible

**Comment by sharkykh** [comment] 2017-08-07 15:33
@miigotu 
https://github.com/SickRage/SickRage/pull/3921#discussion_r126882868
Did you try without it?

**Comment by Ripolin** [comment] 2017-08-08 22:52
@sharkykh @miigotu 
In my case in develop branch, without the `self.include_host = True` Sickrage works agin.

**Comment by HLFH** [comment] 2017-12-10 14:50
Same issue. I switched back to `master`.

**Comment by HLFH** [comment] 2017-12-16 11:08
Thanks @miigotu. We can close this issue.

**Closed** 2017-12-16 11:09 UTC
