### ISSUE TITLE
If a snatched higher quality fails, episode is set to wanted instead of retaining the former lower quality

### ISSUE THREAD

**Issue by monkiibiz** [SickRage/SickRage#1830] opened 2016-05-21 11:04 UTC
Branch/Commit: master/c4fc189279b71802a417195e60dac66f1b85e338
OS: Synology DSM 6.0-7321 Update 6
What you did: Custom quality setting preferring 1080p content, but allowing 720p
What happened: Higher quality release was snatched, but failed to download. Episode status reverted to "Wanted" rather than "Downloaded (720p)". nzbToMedia was used to handle failed download.
What you expected: Episode status reverts to whichever quality was already in library prior to higher quality snatch.
Logs: no logs available
```
no logs available
```

**Comment by SickRage2** [comment] 2016-05-21 11:04
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment] 2016-05-27 13:53
The issue is when a download fails, then NZBtoMedia sets the episode back to `wanted`. (as intended) 
NZBtoMedia doesn't know if a previous episode was downloaded.

This is known and will be fixed when the closer client integration is implemented. (But there is no ETA on that for now.)

**Closed by neoatomic** 2016-05-27 13:53 UTC
