### ISSUE TITLE
[APP SUBMITTED]: mismatched tag: line 9590, column 2

### ISSUE THREAD

**Issue by Lowmach1ne** [SickRage/SickRage#3633] opened 2017-04-17 09:18 UTC
### INFO
Python Version: **2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]**
Operating System: **Linux-4.4.49-1-pve-x86_64-with-centos-7.3.1611-Core**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@1d28b358576b35b101bb0f662858ae5296d2ef8b
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [1d28b35] Unable to connect to theTVDB while creating meta files - skipping - error mismatched tag: line 9590, column 2
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sharkykh** [comment] 2017-04-28 19:08
Caused by a malformed XML downloaded from theTVDB.
Probably got fixed on itself.

**Closed by sharkykh** 2017-04-28 19:08 UTC
Labels: Upstream
