### ISSUE TITLE
SickRage will not start after updating

### ISSUE THREAD

**Issue by sjantzi** [SickRage/SickRage#3559] opened 2017-03-31 14:53 UTC
Help please

python ~/NewSR/SickBeard.py -d
Traceback (most recent call last):
  File "/home/sjantzi/NewSR/SickBeard.py", line 494, in <module>
    SickRage().start()
  File "/home/sjantzi/NewSR/SickBeard.py", line 242, in start
    sickbeard.initialize(consoleLogging=self.console_logging)
  File "/mnt/sdl1/sjantzi/NewSR/sickbeard/__init__.py", line 1100, in initialize
    helpers.manage_torrents_url(reset=True)
  File "/mnt/sdl1/sjantzi/NewSR/sickbeard/helpers.py", line 1897, in manage_torrents_url
    sickbeard.CLIENT_WEB_URLS['torrent'] = ('', torrent_ui_url)[test_exists(torrent_ui_url)]
  File "/mnt/sdl1/sjantzi/NewSR/sickbeard/helpers.py", line 1886, in test_exists
    h = requests.head(url)
  File "/home/sjantzi/NewSR/lib/requests/api.py", line 93, in head
    return request('head', url, **kwargs)
  File "/home/sjantzi/NewSR/lib/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/sjantzi/NewSR/lib/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/sjantzi/NewSR/lib/requests/sessions.py", line 572, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/sjantzi/NewSR/lib/requests/sessions.py", line 646, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'scgi:///home/sjantzi/.config/rtorrent/socket'

**Comment by SickRage2** [comment] 2017-03-31 14:53
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by Mordak603** [comment] 2017-03-31 15:08
Hi,
Same problem here. Sickrage is not restarting after last update.

**Comment by sjantzi** [comment] 2017-03-31 15:22
I rolled back 3 files and it starts up :

sickbeard/__ init __.py
sickbeard/helpers.py
sickbeard/webserve.py

**Comment by joval-sv** [comment] 2017-03-31 15:41
Same here...

08:47:38 INFO::EVENT-QUEUE :: Restarting SickRage with ['/usr/bin/python', u'/sickrage/SickBeard.py', '--datadir=/config/', '--config=/config/config.ini', u'--nolaunch']
Traceback (most recent call last):
  File "/sickrage/SickBeard.py", line 494, in <module>
    SickRage().start()
  File "/sickrage/SickBeard.py", line 242, in start
    sickbeard.initialize(consoleLogging=self.console_logging)
  File "/sickrage/sickbeard/__init__.py", line 1100, in initialize
    helpers.manage_torrents_url(reset=True)
  File "/sickrage/sickbeard/helpers.py", line 1897, in manage_torrents_url
    sickbeard.CLIENT_WEB_URLS['torrent'] = ('', torrent_ui_url)[test_exists(torrent_ui_url)]
  File "/sickrage/sickbeard/helpers.py", line 1886, in test_exists
    h = requests.head(url)
  File "/sickrage/lib/requests/api.py", line 93, in head
    return request('head', url, **kwargs)
  File "/sickrage/lib/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/sickrage/lib/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/sickrage/lib/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/sickrage/lib/requests/models.py", line 293, in prepare
    self.prepare_url(url, params)
  File "/sickrage/lib/requests/models.py", line 353, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
Traceback (most recent call last):
  File "/sickrage/SickBeard.py", line 494, in <module>
    SickRage().start()
  File "/sickrage/SickBeard.py", line 242, in start
    sickbeard.initialize(consoleLogging=self.console_logging)
  File "/sickrage/sickbeard/__init__.py", line 1100, in initialize
    helpers.manage_torrents_url(reset=True)
  File "/sickrage/sickbeard/helpers.py", line 1897, in manage_torrents_url
    sickbeard.CLIENT_WEB_URLS['torrent'] = ('', torrent_ui_url)[test_exists(torrent_ui_url)]
  File "/sickrage/sickbeard/helpers.py", line 1886, in test_exists
    h = requests.head(url)
  File "/sickrage/lib/requests/api.py", line 93, in head
    return request('head', url, **kwargs)
  File "/sickrage/lib/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/sickrage/lib/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/sickrage/lib/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/sickrage/lib/requests/models.py", line 293, in prepare
    self.prepare_url(url, params)
  File "/sickrage/lib/requests/models.py", line 353, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

**Comment by damianharouff** [comment] 2017-03-31 15:45
Going to "me too" this, although with Deluge via scgi:

Mar 31 08:44:55 combine-plex systemd[1]: Starting SickRage Daemon...
Mar 31 08:44:57 combine-plex python2.7[31557]: Traceback (most recent call last):
Mar 31 08:44:57 combine-plex python2.7[31557]:   File "/opt/sickrage/SickBeard.py", line 494, in <module>
Mar 31 08:44:57 combine-plex python2.7[31557]:     SickRage().start()
Mar 31 08:44:57 combine-plex python2.7[31557]:   File "/opt/sickrage/SickBeard.py", line 242, in start
Mar 31 08:44:57 combine-plex python2.7[31557]:     sickbeard.initialize(consoleLogging=self.console_logging)
Mar 31 08:44:57 combine-plex python2.7[31557]:   File "/opt/sickrage/sickbeard/__init__.py", line 1100, in initialize
Mar 31 08:44:57 combine-plex python2.7[31557]:     helpers.manage_torrents_url(reset=True)
Mar 31 08:44:57 combine-plex python2.7[31557]:   File "/opt/sickrage/sickbeard/helpers.py", line 1897, in manage_torrents_url
Mar 31 08:44:57 combine-plex python2.7[31557]:     sickbeard.CLIENT_WEB_URLS['torrent'] = ('', torrent_ui_url)[test_exists(torrent_ui_url)]
Mar 31 08:44:57 combine-plex python2.7[31557]:   File "/opt/sickrage/sickbeard/helpers.py", line 1886, in test_exists
Mar 31 08:44:57 combine-plex python2.7[31557]:     h = requests.head(url)
Mar 31 08:44:57 combine-plex python2.7[31557]:   File "/opt/sickrage/lib/requests/api.py", line 93, in head
Mar 31 08:44:57 combine-plex python2.7[31557]:     return request('head', url, **kwargs)
Mar 31 08:44:57 combine-plex python2.7[31557]:   File "/opt/sickrage/lib/requests/api.py", line 53, in request
Mar 31 08:44:57 combine-plex python2.7[31557]:     return session.request(method=method, url=url, **kwargs)
Mar 31 08:44:57 combine-plex python2.7[31557]:   File "/opt/sickrage/lib/requests/sessions.py", line 468, in request
Mar 31 08:44:57 combine-plex python2.7[31557]:     resp = self.send(prep, **send_kwargs)
Mar 31 08:44:57 combine-plex python2.7[31557]:   File "/opt/sickrage/lib/requests/sessions.py", line 572, in send
Mar 31 08:44:57 combine-plex python2.7[31557]:     adapter = self.get_adapter(url=request.url)
Mar 31 08:44:57 combine-plex python2.7[31557]:   File "/opt/sickrage/lib/requests/sessions.py", line 646, in get_adapter
Mar 31 08:44:57 combine-plex python2.7[31557]:     raise InvalidSchema("No connection adapters were found for '%s'" % url)
Mar 31 08:44:57 combine-plex python2.7[31557]: requests.exceptions.InvalidSchema: No connection adapters were found for 'scgi://172.16.128.117:58846/'
Mar 31 08:44:57 combine-plex systemd[1]: sickrage.service: Control process exited, code=exited status=1
Mar 31 08:44:57 combine-plex systemd[1]: Failed to start SickRage Daemon.
Mar 31 08:44:57 combine-plex systemd[1]: sickrage.service: Unit entered failed state.
Mar 31 08:44:57 combine-plex systemd[1]: sickrage.service: Failed with result 'exit-code'.

**Comment by jangrewe** [comment] 2017-03-31 16:03
Duplicate of #3558, i'd recommend closing this one and continuing in the first.

PS: me too.

**Closed** 2017-03-31 16:20 UTC
Labels: Duplicate, Fixed
