### ISSUE TITLE
Two suggestions to facilitate auto-snatching of shows that air early

### ISSUE THREAD

**Issue by gangrenejellybean** [SickRage/SickRage#3228] opened 2017-02-26 11:10 UTC
I understand that SR avoids grabbing shows until it thinks they've aired to avoid downloading fakes, and support this functionality being default, but I think it could be tweaked slightly to handle the occasional shows that always seem to air before SR thinks they do.

My suggestions:

* Add a user-selectable per-provider option to mark said provider as "trusted". Many of the private torrent providers, such as BTN, MoreThanTV, FreshOnTV, etc, are well-curated and it's exceedingly rare for fake releases to be posted. This option could be used to indicate that early releases found on these providers are safe to grab early.

* Add a per-show option for correcting airdates. When used, SR will consider the airdate of a show to be the TVdb date adjusted by +/- the user-defined amount of time. This would be really useful when a show's episodes air ahead of the TVdb dates by a consistent amount of time.

Thanks for your time and consideration.

**Comment by SickRage2** [comment] 2017-02-26 11:10
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment] 2017-02-26 13:58
Let me guess, you live in Australia? Lol

**Comment by gangrenejellybean** [comment] 2017-02-26 14:50
Yes, I am in Australia. I'm not sure what that has to do with anything, though. SR knows my local timezone and adjusts accordingly. For all but a couple of shows, the time SR thinks they air lines up with reality and they're grabbed right away.

Am I missing something?

**Comment by miigotu** [comment] 2017-02-26 14:52
Australia is the only place I have heard anyone having a problem with shows being released early, thats all haha.  I think there might be a bug in one of the libs we use for timezones in AU, that causes certain timezones/networks to not convert properly.

**Comment by OmgImAlexis** [comment] 2017-02-26 15:00
@gangrenejellybean this is caused by Aussie rippers getting their shit in WA and the networks all being based on the Sydney timezone.

**Comment by gangrenejellybean** [comment] 2017-02-26 22:18
Hmm, I think there's some confusion here.

The kind of early releases I'm thinking of are the ones that show up 1+ day early.

An example: http://thetvdb.com/?tab=season&seriesid=279536&seasonid=676870&lid=7

That says s02e01 airs on feb 19, but that ep appeared online on feb 10. e02 appeared online on feb 21. I anticipate s02e03 will also appear about a week early, too.

**Comment by miigotu** [comment] 2017-02-27 16:24
Its a bit much to go spend a lot of time/effort implementing a whole way of circumventing the protections built into SR for very few select shows.  If you have to only manually DL 1-2 episodes a week, or wait until they are supposed to be released I think its not that big of a deal.  I mean, you had to DL all of your shows manually before =P

**Comment by h3llrais3r** [comment] 2017-03-01 20:04
I assume we can close this? I agree to not invest time/effort in implementing for something that is released before it should actually air. And even if it is released too soon, you will still get it once it's aired.

**Closed** 2017-03-01 20:06 UTC
Labels: Feature Request
