### ISSUE TITLE
Missing episodes not showing under "Schedule Tab"

### ISSUE THREAD

**Issue by vslice24** [SickRage/SickRage#3327] opened 2017-03-05 16:29 UTC
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:master
OS:FreeNas
What you did: updated to latest release
What happened: Missing episodes are not showing up under the schedule tab. I have tried change the range to 14 days but still nothing
What you expected: show episodes that are missing withing the last 7 days
Logs: not sure what logs to add that will help. 
```
PASTE LOGS HERE
```

**Comment by SickRage2** [comment] 2017-03-05 16:29
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sharkykh** [comment] 2017-03-05 16:58
I'm not seeing an issue on my end. Make sure that the episode(s) in question is/are marked as 'Wanted'.

I Just checked by setting an episode to 'Wanted' and revving the setting up to 3000 days.
I got that one episode that is 'Wanted', like expected.

**Comment by vslice24** [comment] 2017-03-05 17:58
@sharkykh Thanks for the response. I have 2 shows, not sure if i can list the shows, that are missing an episode in them each. I setting my window to 3000 like you did and changed an older episode from downloaded to wanted. this then showed as missing when i looked at the schedule tab. i tried changed that status of the show im missing from ignored and then back to misssing but that does not show up. not sure but it looks like its only recently missed shows. one of them aired yesterday

**Comment by sharkykh** [comment] 2017-03-05 18:10
Are the shows that don't show up paused?
Try to show them, change this to 'Shown'
![image](https://cloud.githubusercontent.com/assets/10238474/23589946/b1258002-01df-11e7-9b3e-694c12702ab0.png)

**Comment by vslice24** [comment] 2017-03-05 18:20
@sharkykh they are not paused i tried changed it to shown anyways with now luck. if you change one of your recently download shows to wanted, does it show up in missing?

**Comment by sharkykh** [comment] 2017-03-05 18:27
Yes, but I only have ones from 3 days ago.
I'll look at the code to check if I see a problem.

Please try to see if the episode shows up as missed
when more than a day has passed from it's aired date.

**Comment by vslice24** [comment] 2017-03-05 18:33
so i changed an episode that i aired on 3/3 from downloadde to wanted and it DID show up as missed when i checked. One show im missing the episode that aired on 2/21. i tried making a duplicate copy of a different episide and rename it. I then re-scanned the show so it updated it. Then I changed the status from downloaded to wanted and still no luck. not sure if its just these specific shows.

**Comment by vslice24** [comment] 2017-03-05 19:04
So this problem does seem to be show specific. I changed the status of a different episode, that snatched fine, withing the show from downloaded to wanted and it didn't show up as missing

**Comment by sharkykh** [comment] 2017-03-05 19:07
I wouldn't be so sure..
Try removing the show from SickRage then re adding it...

**Comment by vslice24** [comment] 2017-03-05 19:50
did that as well still not showing up. not sure what log i can send to help debug

**Comment by sharkykh** [comment] 2017-03-05 23:42
What is the show and episode that you're having problems with?
I'll try to reproduce it here.

**Comment by vslice24** [comment] 2017-03-05 23:54
bizzare foods and counting cars

**Comment by sharkykh** [comment] 2017-03-06 00:18
I was able to reproduce.

Missed episodes not showing up when show has no next episode
@miigotu  [In here](https://github.com/SickRage/SickRage/blob/91809083cb82732908357e184acd477138277ef5/sickrage/show/ComingEpisodes.py#L74-L74)

**Comment by vslice24** [comment] 2017-03-06 00:29
so your saying im not going crazy :)

**Comment by miigotu** [comment] 2017-03-06 00:33
I can fix that later

**Comment by sharkykh** [comment] 2017-03-06 00:35
I'm already working on a simple solution
Instead of checking `if next_air_date`
We just do that: https://gist.github.com/sharkykh/8c2d4c16bcd8c5eec81cea3adbe183e9#file-comingepisodes-py-L12

**Comment by miigotu** [comment] 2017-03-06 00:40
I was thinking about a last_aired_date, but if that works...

**Comment by sharkykh** [comment] 2017-03-06 00:41
@miigotu Yeah that works, but not when the status is skipped. Is that correct?
@vslice24 When a new episode airs on one of these shows, does it set the status to `wanted`?

**Comment by miigotu** [comment] 2017-03-06 00:51
Only wanted and unaired should ever show in the schedule.  When one comes up to the airdate it is auto switched to wanted if that is the default episode status of the show.

**Closed** 2017-03-06 02:45 UTC
Labels: Bug / Issue, Confirmed, Fixed

**Comment by vslice24** [comment] 2017-03-06 04:01
Thanks for the fix
