### ISSUE TITLE
Line 275 ilcorsaronero.py in search

### ISSUE THREAD

**Issue by ausghostdog** [SickRage/SickRage#3904] opened 2017-07-05 06:41 UTC
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
Branch: master
Commit: 96b53dee713dc35ebf295d0f37a67b2a36fb4ea3
Version: v2017.06.05-1
Database Version: 44.0

OS: Ubuntu
What you did:nothing

What happened:https://i.imgur.com/pX19e5Y.png, https://i.imgur.com/i1pJ4fq.png
What you expected: https://gist.github.com/OmgImAlexis/c2f56a4214399432ae0cf6063a66bf4d

sickrage is working but get the error

**Comment by OmgImAlexis** [comment] 2017-07-05 07:22
As the issue template states can we please have your logs instead of images.

**Comment by ausghostdog** [comment] 2017-07-05 07:25
It's not letting me add logs, everything I do it says incorrect format, I added a link to one drive one them.

I did try renaming the log to .txt and pastebin says the file is too big.

**Comment by OmgImAlexis** [comment] 2017-07-05 08:20
@miigotu do you have access to ilCorsaroNero? Seems they may have changed their page layout.

**Comment by ausghostdog** [comment] 2017-07-05 10:05
No, I have no idea what it is, just noticed the error, and am reporting it,

**Comment by OmgImAlexis** [comment] 2017-07-05 10:13
I know that's why I tagged miigotu..

**Comment by sharkykh** [comment] 2017-07-05 17:58
ilCorsaroNero is a public site.

@ausghostdog 
Can't reproduce this. What exactly did you search?

**Comment by sharkykh** [comment] 2017-07-05 18:07
@ausghostdog @OmgImAlexis Scratch that. Fixed in develop.
https://github.com/SickRage/SickRage/pull/3890

**Closed by sharkykh** 2017-07-05 18:07 UTC
Labels: Bug / Issue, Need Feedback
