### ISSUE TITLE
Extratorrent: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by albertrdixon** [SickRage/SickRage#2611] opened 2016-11-12 07:32 UTC
Extratorrent began to occasionally spit out these errors while searching for propers. Seems similar to #2444 

### Information

Branch: master
Commit: d15b7003f8663b76d01fcbf0566389b2f31e0564
Version: v2016.10.28-1
Database Version: 44.0
Python: 2.7.11 (default, Jun 2 2016, 13:31:51) [GCC 5.3.0]
Kernel: Linux-4.4.0-22-generic-x86_64
Host OS: Ubuntu 16.04
Container OS: Alpine 3.4.0

### Logs

```
2016-11-11 22:56:32 DEBUG FINDPROPERS :: [ExtraTorrent] :: No data returned from provider
AA
AAAttributeError: 'NoneType' object has no attribute 'group'
AA raise requests_exception
AA File "/src/sickrage/sickbeard/helpers.py", line 1443, in handle_requests_exception
2016-11-11 22:56:32 DEBUG FINDPROPERS :: [ExtraTorrent] :: Traceback (most recent call last):
AAAttributeError: 'NoneType' object has no attribute 'group'
AA raise requests_exception
AA File "/src/sickrage/sickbeard/helpers.py", line 1443, in handle_requests_exception
AATraceback (most recent call last):
2016-11-11 22:56:32 ERROR FINDPROPERS :: [ExtraTorrent] :: [d15b700] Request failed: 'NoneType' object has no attribute 'group'
```

**Comment by SickRage2** [comment] 2016-11-12 07:32
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by Arcanemagus** [comment] 2016-12-27 21:00
Is there any further information that is required for this? I see this somewhat regularly.

**Comment by hackedbellini** [comment] 2017-01-01 15:46
I'm also seeing this for TorrentProject for a while now (at least 2 months).

```
2017-01-01 11:57:00 SEARCHQUEUE-BACKLOG-268156 :: [HD4Free] :: Your authentication credentials for HD4Free are missing, check your config.
```

I'm on the latest `master` commit.

**Comment by Arcanemagus** [comment] 2017-01-01 20:23
@hackedbellini Your error is a completely different issue, it looks like your credentials are missing (and that the TorrentProject provider didn't update the message when it was cloned from HD4Free).

**Comment by hackedbellini** [comment] 2017-01-01 20:26
@Arcanemagus omg sorry about that, I copied the wrong log. This is what I wanted to paste:

```
2017-01-01 17:21:34 SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [338c416] Request failed: 'NoneType' object has no attribute 'group'
```

I saw that I misses the credentials and that is the reason that I wasn't even going to report it. But for some reason I copied by mistake =P

**Comment by rmbleeker** [comment] 2017-01-02 09:01
I'm seeing the same error:

```
2017-01-02 09:48:54 SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [93fbc2b] Request failed: 'NoneType' object has no attribute 'group'
```

**Comment by rmbleeker** [comment] 2017-01-02 21:45
I think this is a duplicate of #2202. It still requires a fix though.

**Comment by NickMolloy** [comment] 2017-01-24 09:34
I believe this issue is because TorrentProject [no longer has an API](https://torrentproject.se/api).
Therefore all requests to it return a HTTP 503 response [e.g](https://torrentproject.se/?filter=2101&s=A+Series+of+Unfortunate+Events+S01E01&showmagnets=on&num=50&out=json)

```cloudflare-scrape``` interprets this 503 as meaning there is a cloudflare token that must be extracted, as 
```if resp.status_code == 503 and resp.headers.get("Server") == "cloudflare-nginx"``` is true. There is no token and so re.search() returns none.

The traceback this causes:


```
Traceback (most recent call last):
  File "/home/nick/git_repos/SickRage/sickbeard/helpers.py", line 1380, in getURL
    headers=headers, cookies=cookies, proxies=proxies, verify=verify
  File "/home/nick/git_repos/SickRage/lib/cfscrape/__init__.py", line 38, in request
    return self.solve_cf_challenge(resp, **kwargs)
  File "/home/nick/git_repos/SickRage/lib/cfscrape/__init__.py", line 78, in solve_cf_challenge
    return self.get(submit_url, **kwargs)
  File "/home/nick/git_repos/SickRage/lib/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/home/nick/git_repos/SickRage/lib/cfscrape/__init__.py", line 38, in request
    return self.solve_cf_challenge(resp, **kwargs)
  File "/home/nick/git_repos/SickRage/lib/cfscrape/__init__.py", line 56, in solve_cf_challenge
    params["jschl_vc"] = re.search(r'name="jschl_vc" value="(\w+)"', body).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
22:04:43 ERROR::SEARCHQUEUE-MANUAL-306304 :: [TorrentProject] :: [c0a21a4] Request failed: 'NoneType' object has no attribute 'group'
```

**Comment by rmbleeker** [comment] 2017-01-24 16:49
Thanks for clearing that up. I get the same error for ExtraTorrent, did they also shut down their api? For now I will disable TorrentProject (and possibly ExtraTorrent) as search providers.

**Comment by NickMolloy** [comment] 2017-01-25 08:58
I can't reproduce the same error for ExtraTorrent. In fact, I don't have any problems snatching from it.
Is that exception only thrown when searching for propers with ExtraTorrent?

**Comment by rmbleeker** [comment] 2017-01-25 13:22
Well this bugreport was originally about ExtraTorrent. I've re-enabled it as a search provider and will report back when I have the error. How do I get the traceback though? I already have debug logging enabled.

**Comment by NickMolloy** [comment] 2017-01-25 13:34
I added a ```traceback.print_exc()``` call in ```sickbeard.helpers.handle_requests_exception()``` to get that traceback. Hopefully debug logging should be enough.

**Comment by rmbleeker** [comment] 2017-01-26 15:22
In the case of ExtraTorrent the error seem to pop up only when searching for propers, as you suspected.
```
2017-01-26 14:04:22 FINDPROPERS :: [ExtraTorrent] :: [25cdaec] Request failed: 'NoneType' object has no attribute 'group'
```

**Comment by nastarius** [comment] 2017-02-08 00:28
SickRage Info:
Branch: master
Commit: 7e6e0575542c3f3e5476663532b1357f3ae1e902
Version: v2017.02.2-1
Database Version: 44.0
  Python Version: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
  SSL Version: OpenSSL 1.0.2h 3 May 2016
  OS: Windows-7-6.1.7601-SP1
  Locale: en_US.cp1252

2017-02-07 16:53:30 INFO SEARCHQUEUE-BACKLOG-70355 :: [ExtraTorrent] :: Performing season pack search for ThunderCats
AA 
AA AttributeError: 'NoneType' object has no attribute 'group'
AA raise requests_exception
AA File "C:\SickRage\sickbeard\helpers.py", line 1433, in handle_requests_exception
AA AttributeError: 'NoneType' object has no attribute 'group'
AA raise requests_exception
AA File "C:\SickRage\sickbeard\helpers.py", line 1433, in handle_requests_exception
AA Traceback (most recent call last):
2017-02-07 16:52:44 ERROR SEARCHQUEUE-BACKLOG-70355 :: [ExtraTorrent] :: [7e6e057] Request failed: 'NoneType' object has no attribute 'group'
2017-02-07 16:51:39 INFO SEARCHQUEUE-BACKLOG-70355 :: [ExtraTorrent] :: Performing episode search for ThunderCats

**Comment by trancen** [comment] 2017-02-13 14:49
I'm getting this error only with TORRENTPROJECT

2017-02-13 09:43:28 SEARCHQUEUE-MANUAL-262305 :: [TorrentProject] :: [5ba0a52] Request failed: 'NoneType' object has no attribute 'group'

2017-02-13 09:47:00 ERROR SEARCHQUEUE-MANUAL-79836 :: [TorrentProject] :: [5ba0a52] Request failed: 'NoneType' object has no attribute 'group'
AA 
AA AttributeError: 'NoneType' object has no attribute 'group'
AA raise requests_exception
AA File "/var/www/sickrage/sickbeard/helpers.py", line 1433, in handle_requests_exception
AA AttributeError: 'NoneType' object has no attribute 'group'
AA raise requests_exception
AA File "/var/www/sickrage/sickbeard/helpers.py", line 1433, in handle_requests_exception
AA Traceback (most recent call last):
2017-02-13 09:46:55 ERROR SEARCHQUEUE-MANUAL-79836 :: [TorrentProject] :: [5ba0a52] Request failed: 'NoneType' object has no attribute 'group'
AA 
AA AttributeError: 'NoneType' object has no attribute 'group'
AA raise requests_exception
AA File "/var/www/sickrage/sickbeard/helpers.py", line 1433, in handle_requests_exception
AA AttributeError: 'NoneType' object has no attribute 'group'
AA raise requests_exception
AA File "/var/www/sickrage/sickbeard/helpers.py", line 1433, in handle_requests_exception
AA Traceback (most recent call last):

**Comment by NickMolloy** [comment] 2017-03-01 13:40
I think the root cause of these issues is that there are intermittent failures with ExtraTorrent, and it returns a HTTP 503. The cloudflare-scrape library mistakenly interprets this as meaning there is a cloudflare challenge it must bypass, which results in the `AttributeError` exception.

This problem seems to have been fixed in cloudflare-scrape in https://github.com/Anorov/cloudflare-scrape/commit/be0a5364055f1f64cb5044cd15a0530c79c2ab20, so upgrading the version used in SickRage should fix this issue.

**Comment by sharkykh** [comment] 2017-03-01 14:06
Just tested by bumping cloudflare-scrape's version to the latest (locally).
Seems to fix the `Request failed: 'NoneType' object has no attribute 'group'` error, and replaces it with the _**right one**_:
```
[TorrentProject] :: Request failed: 503 Server Error: Service Temporarily Unavailable for url: https://torrentproject.se/?filter=2101&s=***********&showmagnets=on&num=50&out=json
```
Because TorrentProject has no API search for now.

ExtraTorrent very rarely puts out this error...
So I think we just need to push a fix and see if it doesn't pop out anymore.

@NickMolloy Do you want to do it?

**Closed** 2017-03-02 06:53 UTC

**Comment by trancen** [comment] 2017-03-04 17:55
The errors with this issue seem to have stopped for me after several months.
