### ISSUE TITLE
Sickrage moving shows to root instead of tv show folder. 

### ISSUE THREAD

**Issue by kendog819** [SickRage/SickRage#3462] opened 2017-03-21 22:36 UTC
![momsickrage](https://cloud.githubusercontent.com/assets/11353628/24173834/286f7560-0e64-11e7-9e8a-0b3592ad9fe9.PNG)

Started a few days ago, TV shows are 'moving' (not copied) to the root instead of into their respected TV Show Folder or Season Folder.

![capture](https://cloud.githubusercontent.com/assets/11353628/24174065/1aef1ad4-0e65-11e7-9291-aee5470aa4c5.PNG)

Transmission sends Movies to the correct place after download, so I have ruled Transmission out as being the issue.

Any help is appreciated,
Ken

**Comment by SickRage2** [comment] 2017-03-21 22:36
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sharkykh** [comment] 2017-03-22 04:43
First make sure the folder that you set Transmission to download into **isn't** in your tv root dir.

Post debug logs and your post processing settings.

**Comment by kendog819** [comment] 2017-03-22 17:19
Hi sharkykh,

As stated, Movies downloaded thru transmission are downloading to the correct "Completed Downloads" folder. So I don't believe it is Transmisson.

Debug Log: https://gist.github.com/kendog819/ef1d713b4f6c1e4692828fa12ff4eccb

![pp1](https://cloud.githubusercontent.com/assets/11353628/24211365/297e19c2-0f02-11e7-962d-34af793c3be4.PNG)
![pp2](https://cloud.githubusercontent.com/assets/11353628/24211366/297e12ce-0f02-11e7-86cd-151e2628b3c3.PNG)

**Comment by sharkykh** [comment] 2017-03-22 17:36
Some of the files in the debug log didn't even process (couldn't figure out season and episode from blindspot.214r and such) and some of the files weren't really processed because you already have the episodes and they're the same size:
```
2017-03-22 13:11:30 INFO     POSTPROCESSOR-AUTO :: File exists and new file is same size, pretending we did something
2017-03-22 13:11:30 DEBUG    POSTPROCESSOR-AUTO :: File D:\Z The Beginning of Everything\Season 01\1x10 Best of All.mkv is the same size as E:\downloads\completed downloads\Z.The.Beginning.of.Everything.S01E10.WEBRip.X264-DEFLATE\z.the.beginning.of.everything.s01e10.webrip.x264-deflate\Z.The.Beginning.of.Everything.S01E10.WEBRip.X264-DEFLATE.mkv
```

In any case, I don't see anything in this debug log that relates to this issue. The folders paths I'm seeing are the correct ones. I would need a log for a post-processing that you know caused this issue.

Also we just released a new version, and I believe your SickRage has updated just after the post processing that you sent finished.
In that release I reverted some changes that caused big issues,
so you should check again to see if maybe it was fixed now.

**Comment by kendog819** [comment] 2017-03-22 18:35
No change, downloading some new  shows right now to see if I can grab a proper log for you.

Thanks!

**Comment by kendog819** [comment] 2017-03-22 19:11
https://gist.github.com/kendog819/fae32708aac3ceced217f24533db0889

I'm noticing many shows that arent part of anything i've ever downloaded

"Unable to match NHL.2017.03.21.Winnipeg.vs.Philadelphia.HDTV.x264-GAMETiME to a show in your database."

90% of those "unable to match" aren't anything I'm familiar with, nor are they on my computer that I can see. I don't even watch hockey..

**Comment by kendog819** [comment] 2017-03-22 19:17
2017-03-22 15:14:33 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from One Day at a Time (2017)
2017-03-22 15:04:36 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from One Day at a Time (2017)
2017-03-22 14:54:35 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from One Day at a Time (2017)
2017-03-22 14:44:34 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from One Day at a Time (2017)

At 15:09 an episode completed downloading, and was instantly moved to the wrong location..

![pp3](https://cloud.githubusercontent.com/assets/11353628/24216473/b270d6ce-0f12-11e7-8ac4-a4b427b30e08.PNG)

**Comment by kendog819** [comment] 2017-03-24 00:25
Any other suggestions? :-)

**Comment by sharkykh** [comment] 2017-03-24 05:34
> I'm noticing many shows that arent part of anything i've ever downloaded

Don't worry about it, it's how searches are preformed (it parses all of the release titles and checks if you have the show in your database)


Maybe the issue is in the root dirs?
What are the root dirs set in General Config?
What is the show dir set in ` One Day at a Time (2017)` show config?

**Comment by kendog819** [comment] 2017-03-24 13:26
![general config](https://cloud.githubusercontent.com/assets/11353628/24296078/f20a42d6-1073-11e7-9415-c46eba5db0f3.PNG)
![show config](https://cloud.githubusercontent.com/assets/11353628/24296077/f20a24d6-1073-11e7-8384-fb2e5b9ae158.PNG)
![show status](https://cloud.githubusercontent.com/assets/11353628/24296079/f20b6058-1073-11e7-88fb-69195fe838e8.PNG)

They look correct to me :-/

**Comment by kendog819** [comment] 2017-03-24 14:40
Found someone who had same issue in 2015: https://www.sickrage.ca/forums/forum/help-support/bug-issue-reports/31137-post-processing-placing-files-in-wrong-directory

**Comment by miigotu** [comment] 2017-03-24 23:39
Try putting the shows root into a subfolder of D:\, not at the root of the drive.

**Comment by kendog819** [comment] 2017-03-25 01:22
I can try.. but it's been fine for 2 years running as is.. 

Will I have to change each shows destination afterwards also?

**Comment by kendog819** [comment] 2017-03-25 01:24
Or is what you are saying is to change every shows directory? 

I have 30 plus shows...

**Comment by miigotu** [comment] 2017-03-25 01:26
Just do it with one show, manual search one episode, let it process, and see what happens....

**Comment by miigotu** [comment] 2017-03-25 01:26
Your log doesnt show anything being moved, so I cant help beyond that.

**Comment by kendog819** [comment] 2017-03-25 17:17
i changed the location of the show from D: to D:\TV SHows\Show. But show is still being moved directly to the root, D:

Not sure where to go from here. It is 100% Sickrage doing it, but like you say, it isn't printing anything to the log, so not sure what is actually happening. 

So.... Where to go from here? Is there an easy way to reinstall without losing all of my settings, etc.?

**Comment by kendog819** [comment] 2017-03-25 19:27
Ok, I did a backup of SR, uninstalled old, didn't save settings, installed new, and imported backup. Still same issue. 

Tried new show, Log shows this as soon as show finishes.So, auto post processor is starting, but the show is not post processing, it is just moving the downloaded file, to the root still.
  
2017-03-25 15:21:25 INFO     POSTPROCESSOR-AUTO :: Auto post processing task for E:\downloads\completed downloads completed
2017-03-25 15:21:25 INFO     POSTPROCESSOR-AUTO :: Successfully processed
2017-03-25 15:21:25 DEBUG    POSTPROCESSOR-AUTO :: E:\downloads\completed downloads : No processable items found in folder
2017-03-25 15:21:25 DEBUG    POSTPROCESSOR-AUTO :: Processing folder E:\downloads\completed downloads
2017-03-25 15:21:25 INFO     POSTPROCESSOR-AUTO :: Processing E:\downloads\completed downloads
2017-03-25 15:21:25 DEBUG    POSTPROCESSOR-AUTO :: Processing in folder E:\downloads\completed downloads
2017-03-25 15:21:25 INFO     POSTPROCESSOR-AUTO :: Beginning auto post processing task: E:\downloads\completed downloads
2017-03-25 15:21:22 INFO     POSTPROCESSOR :: Auto post processing task for E:\downloads\completed downloads was added to the queue
2017-03-25 15:21:22 DEBUG    POSTPROCESSOR :: Starting new thread: POSTPROCESSOR


I have no clue where to go from here...

**Comment by miigotu** [comment] 2017-03-25 19:28
If it isnt being processed, sickrage isnt moving anything.  The only time it moves anything is during post processing.

**Comment by kendog819** [comment] 2017-03-25 19:31
@miigotu Maybe I am not wording it right, but it is 100% being moved by something other than Transmission. And seeing this box only has Transmission, Sickrage, and Plex installed on it. There isn't many other choices. 

I can manually download a movie, and it goes to the correct "Completed Downloads" folder where it is set in transmission, and stays there. Shows that are running thru sickrage get moved to the wrong place...

**Comment by kendog819** [comment] 2017-03-25 19:32
What would you suggest I do from here?

**Comment by miigotu** [comment] 2017-03-25 19:33
Edit permissions on D:\, and allow "Everyone" full control, recusrsively.

**Comment by sharkykh** [comment] 2017-03-25 19:35
There is nothing in the completed directory.
You gotta check Transmission again. Maybe you're running some kind of post download script? Check again if Transmission moves completed torrents to another location on completion.

**Comment by kendog819** [comment] 2017-03-25 19:37
@miigotu 

Permissions were already set to that..

![image](https://cloud.githubusercontent.com/assets/11353628/24325522/e4573254-1170-11e7-8736-2c9dfe536eda.png)

**Comment by kendog819** [comment] 2017-03-25 19:39
@sharkykh 

![image](https://cloud.githubusercontent.com/assets/11353628/24325535/1ea47e12-1171-11e7-9b00-f82c7d97369c.png)

No scripts running, directories set correctly, same way they have been for about 2 years.

**Comment by sharkykh** [comment] 2017-03-25 19:42
How I see it now is,
You're saying downloaded shows move to D:\ on completion and Movies don't.
If that happens as soon as the download finishes it has to be your client, or something (like a post download script) that being run by the client.

**Comment by kendog819** [comment] 2017-03-25 19:44
@sharkykh 

Then why wouldn't the movies also be moving there? There is no scripts running. SHows that in the Transmission preferences I posted above.

**Comment by sharkykh** [comment] 2017-03-25 19:45
My reason for saying that was that some clients let you move files to folders based on category/label

**Comment by kendog819** [comment] 2017-03-25 19:47
Transmission seems fairly basic, and I'm not that knowledgable, I haven't set any sort of scripts or adcvanced things like that, and I am the only one who uses this PC. 

I can give you or @miigotu Teamviewer access if you would like to take a look, and see if you can see anything out of whack 1st hand.

**Comment by sharkykh** [comment] 2017-03-25 19:48
And,
SickRage logs all of its attempts when in debug mode - if it's not logged then I really don't think it's responsible.
Can you try copying a downloaded folder (like the ones being moved automatically) back to completed downloads folder and let SickRage run auto-postprocessing on it?

**Comment by kendog819** [comment] 2017-03-25 19:52
Will try that in 1 moment.

I am currently downloading a show that is not in my SR database, and seeing where it goes.

**Comment by kendog819** [comment] 2017-03-25 20:03
As suspected, manually downloading a TV Show goes to completed downloads as it should.

![image](https://cloud.githubusercontent.com/assets/11353628/24325685/7f2cd538-1174-11e7-993e-660143df4d74.png)

**Comment by sharkykh** [comment] 2017-03-25 20:06
Wait a second...
check
http://localhost:8081/config/search/
Make sure **Downloaded files location** is empty

**Comment by miigotu** [comment] 2017-03-25 20:07
@sharkykh the problem is that the download files location IS empty, so they are downloaded to the prog root.

If you manually add it to transmission, it does not automatically go to the same location as sickrage sends files to.

You need to set this setting in SickRage, because it does not matter what paths you have set in transmission as long as the move_completed is set
![image](https://cloud.githubusercontent.com/assets/390379/24325705/ec04d8cc-115b-11e7-9f0b-5b5863572bc6.png)

Set this same path in post processing path.

**Comment by sharkykh** [comment] 2017-03-25 20:09
That's weird cause it says blank for client default - and his default is [the completed downloads directory](https://cloud.githubusercontent.com/assets/11353628/24325535/1ea47e12-1171-11e7-9b00-f82c7d97369c.png):

**Comment by kendog819** [comment] 2017-03-25 20:11
Manually PP'd a file, watching this screen, doesn't give me info or let me know it was completed as it formerly did....

![image](https://cloud.githubusercontent.com/assets/11353628/24325716/59f3c65e-1175-11e7-8195-e4c15e9805ae.png)

But...

![image](https://cloud.githubusercontent.com/assets/11353628/24325727/9fa8b006-1175-11e7-802d-2b1a5350bc4e.png)

**Comment by sharkykh** [comment] 2017-03-25 20:12
Change it to debug and post that log here

**Comment by miigotu** [comment] 2017-03-25 20:13
If you would read the checkboxes you would have seen this on the manual pp page:
![image](https://cloud.githubusercontent.com/assets/390379/24325735/b041277c-115c-11e7-8443-b42666523a08.png)
Don't get snarky now, because trust me I remember who you are =P

**Comment by kendog819** [comment] 2017-03-25 20:13
https://gist.github.com/kendog819/ef8cc149ba66434b7e6318c1bb7c0445

**Comment by kendog819** [comment] 2017-03-25 20:14
@miigotu I did miss that, thanks ;)

**Comment by miigotu** [comment] 2017-03-25 20:16
Go to `http://ip:port/config/search/`
Click the tab `Torrent Search`
Set `Downloaded files location` to `E:\downloads\ completed downloads`
Save.
Go to `http://ip:port/config/postProcessing/
Set `Post Processing Dir` to `E:\downloads\ completed downloads`
Make sure `Enable` is checked.
Save.
Done.

**Comment by kendog819** [comment] 2017-03-25 20:22
@miigotu 

That seems to be where my problem was at. Somehow "D:" ended up in that box, no clue how that happened.

Thanks so much to you and @sharkykh for the help.

**Comment by miigotu** [comment] 2017-03-25 20:24
You are right, it was not Transmission. And it wasnt SickRage either =P
https://github.com/SickRage/SickRage/issues/3462#issuecomment-288297245

**Comment by sharkykh** [comment] 2017-03-25 20:25
:rofl:

**Closed** 2017-03-25 20:25 UTC

**Comment by kendog819** [comment] 2017-03-25 20:27
Well, it was Sickrage.. but it wasn't sickrage's fault..lol
