### ISSUE TITLE
Sickrage with Synology DSM 5.2 Download Station - Massive message in log: Request failed: 404 Client Error 

### ISSUE THREAD

**Issue by lediabolo** [SickRage/SickRage#3517] opened 2017-03-29 19:30 UTC
Hello,

Since one or two days, I've an issue with Sickrage, It cannot connect at Synology Download Station

SickRage Info:
Branch: master
Commit: 7ba52ea56efd8ceb72e2fc23ba344c8599e75b0d
Version: v2017.03.28-2
Database Version: 44.0
  Version de Python: 2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]
  Version SSL: OpenSSL 1.0.2j 26 Sep 2016
  OS: Linux-3.10.35-x86_64-with-glibc2.2.5
  Local: en_US.UTF-8

SickRage is installed on a Virtual Machine (VMware)  XPenology with DSM 5.2-5967 Update 2 

What you did: I activated SickRage auto update feature
What happened: many messages in the top of SickRage web page and many error message in the sickrage log (journal), and no connexion between Sickrage et Synology Download Station

Complete Logs:
https://mega.nz/#!EAVnxTBb!s5-Y8HKo2DNqPfXGQ0d4mDVE0ZCGLbDHedzK2SmcWII

Extract some LOGS:
> 2017-03-29 21:13:39 INFO Thread-15 :: Request failed: 404 Client Error: Not Found for url: https://192.168.1.65:5001/download/ 
> 2017-03-29 21:13:39 INFO Thread-14 :: Request failed: 404 Client Error: Not Found for url: https://192.168.1.65:5001/download/
> 2017-03-29 21:13:38 INFO Thread-15 :: Request failed: 404 Client Error: Not Found for url: https://192.168.1.65:5001/download/
> 2017-03-29 21:13:37 INFO Thread-14 :: Request failed: 404 Client Error: Not Found for url: https://192.168.1.65:5001/download/
> 2017-03-29 21:13:36 INFO Thread-15 :: Request failed: 404 Client Error: Not Found for url: https://192.168.1.65:5001/download/
etc...
``
(see screenshot)

![snag-0147](https://cloud.githubusercontent.com/assets/22579607/24480797/85b437fa-14e6-11e7-8baa-e1bfa2d08c21.jpg)

So, Sickrage cannot connect on Download Station of Synology :(
Before the Sickrage auto update, no URL error 

Any idea ??
Thanks
 
François

**Comment by SickRage2** [comment] 2017-03-29 19:30
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [ ] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by lediabolo** [comment] 2017-03-29 23:25
maybe, to help, below my Torrent Search Config:
![snag-0149](https://cloud.githubusercontent.com/assets/22579607/24480948/a3def3ea-14e7-11e7-97f2-21fe0ada9c84.jpg)

**Comment by sharkykh** [comment] 2017-03-29 23:49
Don't know what the cause of the 404 error, and can't open a zip file right now (on mobile).
But,
>When I click on "Test connection" button, no action in background. In the past, this button worked with no error, the connection was fine

Currently there is an issue with all of the javascript ( will be fixed by #3512 )

**Comment by consenti** [comment] 2017-03-30 00:54
I'm having this problem with Synology DS also.  The error is caused SickRage incorrectly adding "/download/" after the "Torrent host:port" entry provided by the user in Torrent Search settings.  If someone could please just stop the app from appending "/download/" in the script, then the error should go away.

**Comment by miigotu** [comment] 2017-03-31 04:16
Did you try doing what the site message says?

**Comment by consenti** [comment] 2017-03-31 13:51
Yes.  My torrent IP port entry for Synology DS is https://192.168.1.18/download/        This entry passes the "Test Connection" test and works to download torrents from DS.  However, somewhere within program the system tries to connect to https://192.168.1.18/download/download/  (see logs above to view resulting 404 error).      So, something within the system is appending an additional text string of "download/".  This is incorrect.  It shouldn't append my working entry from my Torrent Search serttings with extra text.  It should just use my entry of https://192.168.1.18/download/ without adding text

**Closed** 2017-03-31 14:20 UTC

**Comment by lediabolo** [comment] 2017-04-01 16:46
Great, I updated Sickrage today, with the last fixes:
- Test connection button works fine
- No more client errors in log about the Synology download URL

Thanks very much for the good job
