### ISSUE TITLE
rTorrent torrents are loaded but not started anymore

### ISSUE THREAD

**Issue by mr-orange** [SickRage/SickRage#2880] opened 2017-01-12 14:00 UTC
Hi I'm using rTorrent 0.9.6 on a linux machine and torrent are loaded without any problem, however they are never started automatically. Was working ok in December and this problem appear one week ago.
Let me know if you need other info because log are useless (no error are shown), anyway thanks for this sickbeard forks.
 
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by SickRage2** [comment] 2017-01-12 14:00
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by rubikscube28** [comment] 2017-01-12 15:20
I am experiencing the same with the added issue that the torrent is not labelled any more.

**Comment by lowelln1618** [comment] 2017-01-12 19:35
I am experiencing the same issue. I have to manually go into rtorrent to start them. I can provide logs if that will help.

**Comment by liranbg** [comment] 2017-01-13 08:32
Go to Search Settings -> Torrent Search tab -> make sure that Start torrent paused is unchecked

**Comment by mr-orange** [comment] 2017-01-13 08:34
Yes it's uncheked.



		_____________________________

**Comment by liranbg** [comment] 2017-01-13 08:38
Well, I guess it requires some investigation.

Please enable debug logging in SickRage settings and reproduce the error.
once its done, fill the the Qs below

Branch/Commit:
OS:
What you did:
What happened:
What you expected:
Logs:

**Comment by mr-orange** [comment] 2017-01-13 08:53
the debug logging is useless because any error is shown.

What you did: Manual searching an episode
What happened: Episode was found and rtorrent client download the torrent
metadata after that the episode is paused and not started.
What you expected: Automatic start of episode because I do not flag start
torrent paused options.

**Comment by miigotu** [comment] 2017-01-13 12:59
Make sure `Start torrent paused` is not checked on `/config/search/` on the torrent tab. Paused start was just added to rTorrent recently, it was not available in SR before.

**Comment by miigotu** [comment] 2017-01-13 13:00
Are these all magnet calls or also .torrent added?

**Comment by rubikscube28** [comment] 2017-01-13 14:53
I'm am using RPC, I guess that would be magnet call. The black hole folder option never worked reliably for me.

**Comment by arjenanker** [comment] 2017-01-13 15:40
Had the same problems, did a rollback to before commit 5e1842ca4089c9de7488143bb013e9f9be07a483 and my issues are gone.

The torrent would be added with status stopped (closed in the rtorrent client itself), no label, no download folder. I think everything is magnet link, no torrent files.

Nothing would be shown in the debug log, it just says everything worked.

**Comment by mr-orange** [comment] 2017-01-13 15:44
Hi migotu, it was a magnet and the stop torrent options is not flagged. 



		_____________________________

**Comment by miigotu** [comment] 2017-01-13 15:48
@arjenanker could you try adding `torrent.start()` just under the `if verify_load:` that is on line 245 of `lib/rtorrent/__init__.py`
Methinks thats the issue.
https://github.com/SickRage/SickRage/commit/5e1842ca4089c9de7488143bb013e9f9be07a483#diff-33878acf9434aa074045d228eade8661L256

**Comment by arjenanker** [comment] 2017-01-13 15:54
I can't right now, don't really have the time. And it took me a lot of effort to roll back 25 commits. Maybe one of the others with the issue could try this?

Would adding that line also add the label and download dir? It sounds like it would only start the download.

**Comment by miigotu** [comment] 2017-01-13 20:12
Im thinking it doesnt return a torrent back to the SR client to be able to set the label or dir on since it hasnt resolved yet.

I dont have an rTorrent setup to set with and its a pita to get set up with that.

**Comment by klingscope** [comment] 2017-01-13 22:22
In line 72 of rtorrent_client.py it has the following code that was updated in commit 2c4eddb.

torrent = self.auth.load_magnet(result.url, result.hash, **verify_load=not sickbeard.TORRENT_PAUSED**)

Regarding the third argument that was added in that commit, was this supposed to be assignment (=) or a logical comparison (==)?

**Comment by mr-orange** [comment] 2017-01-13 23:30
> @arjenanker could you try adding torrent.start() just under the if verify_load: that is on line 245 of lib/rtorrent/__init__.py
Methinks thats the issue.
5e1842c#diff-33878acf9434aa074045d228eade8661L256

@miigotu  your suggestion is not working.
If you need I can set you a VPN to my linux box where i have the rtorrent client so you can debug and see what is not working.
Anyway I've just reverted your last change on rtorrent lib and now is all working good.
Let me know.

**Comment by miigotu** [comment] 2017-01-14 03:47
@klingscope assignment. You wouldnt be able to to comparison with verify_load becuse verify_load is not defined before that call, its just a parameter.

@mr-orange might be a good idea, you can email me miigotu@gmail

**Comment by arjenanker** [comment] 2017-01-16 13:11
Issue seems to be in lib/rtorrent/__init__.py. Backed that file up just in case.

Did a git pull and torrents were added as stopped again. Copied that file back and it started working again. Something in fixing the bs code in rtorrent lib seems to be messing up in this specific file, for magnet loading. Just tried, if the only search provider available has no magnet links, only torrents, it does work.

**Comment by mr-orange** [comment] 2017-01-19 10:57
@miigotu any new on this issue?
For semplicity could you revert rtorrent lib?
Please let we know.

**Comment by miigotu** [comment] 2017-01-19 10:58
I havent been able to connect to the vpn yet, ubuntu zesty doesnt have the vpn plugin for your params. Ill try to get connected to it soon, just been busy with life/work

**Comment by mr-orange** [comment] 2017-01-19 17:06
Hi miigoutu You can install Shrew Soft VPN client in ubuntu zesty to manage
IPSec vpn connection.
Let me know if you can connect.

**Comment by miigotu** [comment] 2017-01-19 17:52
@mr-orange thanks for the vpn, but I just spun up a prebuilt docker image https://github.com/diameter/rtorrent-rutorrent

Working on it now

**Closed** 2017-01-19 18:16 UTC
