### ISSUE TITLE
cant start sicktage after upgrade qnap to 4.3.2

### ISSUE THREAD

**Issue by papampi** [SickRage/SickRage#2669] opened 2016-12-05 16:19 UTC
Upgraded my qnap nas to 4.3.2, now sickrage gives this error :
```

Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/tornado/web.py", line 1446, in _execute
    result = self.prepare()
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/tornado/web.py", line 2174, in prepare
    raise HTTPError(self._status_code)
HTTPError: HTTP 404: Not Found
```

**Comment by SickRage2** [comment] 2016-12-05 16:19
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by papampi** [comment] 2016-12-11 16:15
tried to remove and reinstall with no luck, rolled back to QTS 4.2.2

**Comment by tigertim08** [comment] 2016-12-19 22:52
I have the same problem...

`[~] #  /etc/init.d/sickbeard-tvrage.sh start
x86_64
SickBeard-TVRage prestartup checks...
 Checking for git...  Found!
Looking for /usr/bin/python2.7
Looking for /usr/local/bin/python2.7
Looking for /opt/bin/python2.7
Looking for /Apps/opt/bin/python2.7
Looking for /opt/QPython2/bin/python2.7
Found Python Version 2.7.12 at /opt/bin/python2.7
Updating SickBeard-TVRage
/etc/init.d/sickbeard-tvrage.sh: line 99: /Apps/bin/git: No such file or directory
/etc/init.d/sickbeard-tvrage.sh: line 99: /Apps/bin/git: No such file or directory
/etc/init.d/sickbeard-tvrage.sh: line 100: cd: /share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage: No such file or directory
Starting SickBeard-TVRage
/etc/init.d/sickbeard-tvrage.sh: line 111: cd: /share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage: No such file or directory
/opt/bin/python2.7: can't open file 'SickBeard.py': [Errno 2] No such file or directory`

Tried do uninstall it and make it new but still it does not work. Does anybody has an idea? 

Thanks in advance
tigertim08

**Comment by papampi** [comment] 2016-12-22 12:44
any news on this ?
could you make it work ?

**Comment by miigotu** [comment] 2016-12-23 09:23
What happens if you just type `git --version` on the command line?

**Comment by papampi** [comment] 2016-12-23 09:38
I rolled back to 4.2.2 for now till I can use sickrage, but I remember git was installed.
I think it has an architecture problem as mentioned in change log :
https://www.qnap.com/qts/4.3-release-note/en/
QTS 4.3.x uses 64-bit system architecture and may not support some 32-bit applications. Download the QTS 64-bit compatibility tool and install in QTS.

**Comment by miigotu** [comment] 2016-12-23 09:40
Python code is architecture independent. As long as you have git and python it will work

**Comment by papampi** [comment] 2016-12-23 13:16
I will wait for 4.3 official release then will upgrade and check again ,

**Comment by tigertim08** [comment] 2016-12-23 15:32
I think the problem is that git is not working correct with the 4.3 version. 

I have installed it serval times and it always says that everythink worked fine and I can use git now. But if I am going into the terminal and type 'git --version' I get the message 

`-sh: /Apps/bin/git: No such file or directory`

Any ideas how to fix that?

**Comment by neoatomic** [comment] 2016-12-30 16:04
It has always been a hassle to install SR on a Qnap. Mainly the packages and there versions/locations.
There should be a link in the wiki to a topic in the qnap forum, there might be more info about this current 4.3 update and compatibility with packages/SR

**Comment by miigotu** [comment] 2016-12-30 16:06
I think we need to go to a source install method for Qnap, since git is always a PITA.  The start script could download a zip or tarball instead of git clone and let it work form there instead

**Comment by miigotu** [comment] 2017-01-01 10:59
You could try this gitless version I made: https://github.com/SickRage/qnap-sickrage/releases/tag/v1.0.1-test

I dont know if it works or even installs, because I have no qnap to test with. This uses wget and tar to grab the latest master tarball and set cur_commit hash in the config.ini, and will update just like the synology does, rather than using git.

**Comment by miigotu** [comment] 2017-01-01 15:32
Your error when typing `git --version on cli`, can probably be fixed with first doing `/etc/inhit.d/git.sh start`

Anyways, please try the test qpkg i made, I did a bunch of work on it but it probably needs some tweaks/touches

**Closed** 2017-01-05 17:01 UTC

**Comment by tigertim08** [comment] 2017-01-07 12:16
Hey Miigotu, 

sorry for the late reply. I tried to install the qpkg put it won't start...

**Comment by miigotu** [comment] 2017-01-07 12:23
Yeah, I dont know if its proper yet, I have no way to test it. Will have to wait until a dev with one can play with it

**Comment by papampi** [comment] 2017-01-08 11:31
I'm waiting for stable 4.3 release 
Its still beta. 
it may be solved on stable.

**Comment by LeFl0w** [comment] 2017-02-05 08:51
Hi,
i succeed making SickBeard-TVRage update through git works again after upgrade to 4.3 on my TS-251+.I did the following sequence (folders can change depending on your installation): 

1. install git-http from Entware
```
opkg install git-http
```

2. go to /Apps/bin and remove the link to git and replace it with Entware one
```
cd /Apps/bin
rm git
ln -s /share/CACHEDEV1_DATA/.qpkg/Entware-ng/bin/git git
```

3. do the same in /Apps/ folder and remove git folder link and replace to Entware one
```
cd /Apps/
rm git
ln -s /share/CACHEDEV1_DATA/.qpkg/Entware-ng/bin/ git
```
Then you can press update on Sickrage.

**Comment by matthewjoliver** [comment] 2017-04-18 09:17
Thanks @LeFl0w that works!

**Comment by papampi** [comment] 2017-04-22 07:06
After upgrade to 4.3.3 stable on my TVS-863 I tried @LeFl0w workaround which failed to start Sickrage again, then removed Sickrage to try the git-less version.
The @miigotu Git-less version didn't work and gave some errors. (Sorry forgot to keep the errors to post for debugging)
Installed a fresh SickRage again
Restored backup and voila ...  every thing works flawless.
Same goes for CouchPotato, had to remove and reinstall it to work.
Thanks.

**Comment by chrisherman** [comment] 2017-04-28 20:20
Would not work when I restored _entire_ QSickBeard directory.
Uninstalling / reinstalling the package and then _only_ restoring .qpkg/QSickBeard/Sick-Beard/DATAS directory from previous backup worked.

**Comment by papampi** [comment] 2017-04-29 05:54
I didnt copied the directories.
I made a backup from backup/restore sickrage menus, installed fresh and then restored that backup.
