### ISSUE TITLE
Anime not being auto processed correctly

### ISSUE THREAD

**Issue by alucarddelta** [SickRage/SickRage#3505] opened 2017-03-28 12:58 UTC
**Branch:** master
**Commit:** a71302bf84136b18ee18d067064c3eef83
**Version:** v2017.0
**Database Version:** 44.0
**OS:** Linux-4.9.10-unRAID-x86_64-with
**What you did:** Placed number of files in the Auto processing directory to be processed. The show is listed as an anime using the Absolute file name (Show.265)
**What happened:** A number of files failed to process or was processed incorrectly. The ones that failed were then deleted and cant be located or recovered.

Screen Shot of "Anime Selected" in file format.
<img width="962" alt="ss of show format" src="https://cloud.githubusercontent.com/assets/20882097/24405770/6db41662-1409-11e7-9cea-69c8b20b52d4.png">

The one file that was processed incorrectly "Episode 155" tuned into "Season 1 Episode 55". Show was named "SHOW 155"

<img width="962" alt="ss of show format2" src="https://cloud.githubusercontent.com/assets/20882097/24405882/bf31914a-1409-11e7-8ed7-c998f086cf94.png">

"SHOW.155", "SHOW.E155" and "SHOW E155" all failed and was deleted by the system and not the user.

In the past other anime were able to be successfully auto processed using the exact same format as above.

NOTE: The file name that is listed in the logs "Naruto Shippuden E154 -.mkv" is incorrect, the correct file name was just "Naruto Shippuden E154.mkv" This was true

**What you expected:** Files to be processed into the corresponding season and episode according to the absolute episode number. EG 155 = Season 8 Episode 04
**Logs:**
```
2017-03-28 22:10:28 INFO POSTPROCESSOR-AUTO :: /downloads/Naruto.Shippuden.153 -.mkv : Processing failed:
2017-03-28 22:10:28 INFO POSTPROCESSOR-AUTO :: /downloads/Naruto.Shippuden.E152 -.mkv : Processing failed:
2017-03-28 22:10:28 INFO POSTPROCESSOR-AUTO :: /downloads/Naruto Shippuden E154 -.mkv : Processing failed:
2017-03-28 22:10:28 INFO POSTPROCESSOR-AUTO :: Some items were not processed.
2017-03-28 22:10:28 WARNING POSTPROCESSOR-AUTO :: Processing Failed
2017-03-28 22:10:28 INFO POSTPROCESSOR-AUTO :: Processing succeeded for /downloads/Naruto Shippuden 155.mkv
2017-03-28 22:09:47 INFO POSTPROCESSOR-AUTO :: Process method is 'move' and src and destination are on the same device, skipping free space check
2017-03-28 22:09:33 INFO POSTPROCESSOR-AUTO :: Processing /downloads/Naruto Shippuden 155.mkv (None)
2017-03-28 22:09:30 WARNING POSTPROCESSOR-AUTO :: Processing failed for /downloads/Naruto.Shippuden.153 -.mkv:
2017-03-28 22:09:30 INFO POSTPROCESSOR-AUTO :: Not enough information to determine what episode this is. Quitting post-processing
2017-03-28 22:09:19 INFO POSTPROCESSOR-AUTO :: Processing /downloads/Naruto.Shippuden.153 -.mkv (None)
2017-03-28 22:09:14 WARNING POSTPROCESSOR-AUTO :: Processing failed for /downloads/Naruto.Shippuden.E152 -.mkv:
2017-03-28 22:09:14 INFO POSTPROCESSOR-AUTO :: Not enough information to determine what episode this is. Quitting post-processing
2017-03-28 22:09:03 INFO POSTPROCESSOR-AUTO :: Processing /downloads/Naruto.Shippuden.E152 -.mkv (None)
2017-03-28 22:08:59 WARNING POSTPROCESSOR-AUTO :: Processing failed for /downloads/Naruto Shippuden E154 -.mkv:
2017-03-28 22:08:59 INFO POSTPROCESSOR-AUTO :: Not enough information to determine what episode this is. Quitting post-processing
2017-03-28 22:08:49 INFO POSTPROCESSOR-AUTO :: Processing /downloads/Naruto Shippuden E154 -.mkv (None)
2017-03-28 22:08:41 INFO POSTPROCESSOR-AUTO :: Processing /downloads
2017-03-28 22:08:41 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /downloads
2017-03-28 22:08:40 INFO POSTPROCESSOR :: Auto post processing task for /downloads was added to the queue
```

Debug logs scrolled when trying to copy, Reproduced using a new file E156
```
2017-03-28 22:49:00 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /downloads completed
2017-03-28 22:49:00 INFO POSTPROCESSOR-AUTO :: /downloads/Naruto Shippuden E156.mkv : Processing failed:
2017-03-28 22:49:00 INFO POSTPROCESSOR-AUTO :: Some items were not processed.
2017-03-28 22:49:00 WARNING POSTPROCESSOR-AUTO :: Processing Failed
2017-03-28 22:49:00 WARNING POSTPROCESSOR-AUTO :: Processing failed for /downloads/Naruto Shippuden E156.mkv:
2017-03-28 22:49:00 INFO POSTPROCESSOR-AUTO :: Not enough information to determine what episode this is. Quitting post-processing
2017-03-28 22:49:00 DEBUG POSTPROCESSOR-AUTO :: Unable to match downloads Naruto Shippuden E156 to a show in your database. Parser result: downloads Naruto Shippuden - E156 [ABD: False] [ANIME: False] [whichReg: [u'no_season_general']]
2017-03-28 22:48:59 DEBUG POSTPROCESSOR-AUTO :: Trying to find downloads naruto shippuden on theTVDB
2017-03-28 22:48:58 DEBUG POSTPROCESSOR-AUTO :: Analyzing name downloads Naruto Shippuden E156.mkv
2017-03-28 22:48:57 DEBUG POSTPROCESSOR-AUTO :: Parse result(release_group): None
2017-03-28 22:48:57 DEBUG POSTPROCESSOR-AUTO :: or Parse result(air_date): None
2017-03-28 22:48:57 DEBUG POSTPROCESSOR-AUTO :: Parse result(episode_numbers): [156]
2017-03-28 22:48:57 DEBUG POSTPROCESSOR-AUTO :: Parse result(season_number): None
2017-03-28 22:48:57 DEBUG POSTPROCESSOR-AUTO :: Parse result(series_name): Naruto Shippuden
2017-03-28 22:48:57 DEBUG POSTPROCESSOR-AUTO :: Parse result not sufficient (all following have to be set). will not save release name
2017-03-28 22:48:57 DEBUG POSTPROCESSOR-AUTO :: Parsed /downloads/Naruto Shippuden E156 into Naruto Shippuden - E156 [ABD: False] [ANIME: False] [whichReg: [u'no_season_general']]
2017-03-28 22:48:57 DEBUG POSTPROCESSOR-AUTO :: Analyzing name /downloads/Naruto Shippuden E156.mkv
2017-03-28 22:48:57 DEBUG POSTPROCESSOR-AUTO :: Unable to match downloads to a show in your database. Parser result: [ABD: False] [ANIME: False] [whichReg: []]
2017-03-28 22:48:56 DEBUG POSTPROCESSOR-AUTO :: Analyzing name downloads
2017-03-28 22:48:54 DEBUG POSTPROCESSOR-AUTO :: Parse result(release_group): None
2017-03-28 22:48:54 DEBUG POSTPROCESSOR-AUTO :: or Parse result(air_date): None
2017-03-28 22:48:54 DEBUG POSTPROCESSOR-AUTO :: Parse result(episode_numbers): [156]
2017-03-28 22:48:54 DEBUG POSTPROCESSOR-AUTO :: Parse result(season_number): None
2017-03-28 22:48:54 DEBUG POSTPROCESSOR-AUTO :: Parse result(series_name): Naruto Shippuden
2017-03-28 22:48:54 DEBUG POSTPROCESSOR-AUTO :: Parse result not sufficient (all following have to be set). will not save release name
2017-03-28 22:48:54 DEBUG POSTPROCESSOR-AUTO :: Parsed Naruto Shippuden E156 into Naruto Shippuden - E156 [ABD: False] [ANIME: False] [whichReg: [u'no_season_general']]
2017-03-28 22:48:53 DEBUG POSTPROCESSOR-AUTO :: Analyzing name Naruto Shippuden E156.mkv
2017-03-28 22:48:52 INFO POSTPROCESSOR-AUTO :: Processing /downloads/Naruto Shippuden E156.mkv (None)
2017-03-28 22:48:50 DEBUG POSTPROCESSOR-AUTO :: Parsed Naruto Shippuden E156.mkv into Naruto Shippuden - E156 [ABD: False] [ANIME: False] [whichReg: [u'no_season_general']]
2017-03-28 22:48:48 DEBUG POSTPROCESSOR-AUTO :: Processing folder /downloads
2017-03-28 22:48:48 INFO POSTPROCESSOR-AUTO :: Processing /downloads
2017-03-28 22:48:48 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /downloads
2017-03-28 22:48:47 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /downloads
```
**How to reproduce:**
1. Added the show as pre normal.
2. During the show creation I selected the Anime Format
3. Once the Meta data was downloaded, I moved the files into the Auto Processing folder with the File names listed above (replaced SHOW with the correct show name)
4. Allowed the system to auto start the task.
5. See results

**Comment by SickRage2** [comment] 2017-03-28 12:58
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by alucarddelta** [comment] 2017-03-29 04:37
I did a clean install of sickrage as a few months back I did do a restore and just added the one show as a test. There is now a new issue being detected still with the auto processing of the anime.

Below is a log of E183. file format "Show ###". SR think's that it is E83 which then come back to season S4xE12 instead of the correct S9xE08

```
2017-03-29 14:26:49 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /TVdownloads completed
2017-03-29 14:26:49 INFO POSTPROCESSOR-AUTO :: /TVdownloads/Naruto Shippuden 183.mkv : Processing failed:
2017-03-29 14:26:49 INFO POSTPROCESSOR-AUTO :: Some items were not processed.
2017-03-29 14:26:49 WARNING POSTPROCESSOR-AUTO :: Processing Failed
2017-03-29 14:26:49 WARNING POSTPROCESSOR-AUTO :: Processing failed for /TVdownloads/Naruto Shippuden 183.mkv:
2017-03-29 14:26:49 INFO POSTPROCESSOR-AUTO :: File exists and new file quality is not in a preferred quality list, marking it unsafe to replace
2017-03-29 14:26:49 DEBUG POSTPROCESSOR-AUTO :: File /Anime/Naruto Shippuden/Season 04/Naruto Shippuden - 4x12 - Target Lock On.mkv is larger than /TVdownloads/Naruto Shippuden 183.mkv
2017-03-29 14:26:49 DEBUG POSTPROCESSOR-AUTO :: Is ep a priority download: False
2017-03-29 14:26:49 DEBUG POSTPROCESSOR-AUTO :: Quality of the episode we're processing: SDTV
2017-03-29 14:26:49 DEBUG POSTPROCESSOR-AUTO :: Naruto Shippuden 183.mkv looks like it has quality SDTV, using that
2017-03-29 14:26:49 DEBUG POSTPROCESSOR-AUTO :: Guessing quality for name Naruto Shippuden 183.mkv, got SDTV
2017-03-29 14:26:48 DEBUG POSTPROCESSOR-AUTO :: Looking up quality for name Naruto Shippuden 183.mkv, got Unknown
2017-03-29 14:26:47 DEBUG POSTPROCESSOR-AUTO :: Looking up quality for name TVdownloads, got Unknown
2017-03-29 14:26:47 DEBUG POSTPROCESSOR-AUTO :: Retrieving episode object for 4x12
2017-03-29 14:26:47 DEBUG POSTPROCESSOR-AUTO :: Parse result(release_group): None
2017-03-29 14:26:47 DEBUG POSTPROCESSOR-AUTO :: or Parse result(air_date): None
2017-03-29 14:26:47 DEBUG POSTPROCESSOR-AUTO :: Parse result(episode_numbers): [12]
2017-03-29 14:26:47 DEBUG POSTPROCESSOR-AUTO :: Parse result(season_number): 4
2017-03-29 14:26:47 DEBUG POSTPROCESSOR-AUTO :: Parse result(series_name): Naruto Shippuden
2017-03-29 14:26:47 DEBUG POSTPROCESSOR-AUTO :: Parse result not sufficient (all following have to be set). will not save release name
2017-03-29 14:26:47 DEBUG POSTPROCESSOR-AUTO :: Using cached parse result for: Naruto Shippuden 183
2017-03-29 14:26:43 DEBUG POSTPROCESSOR-AUTO :: Analyzing name Naruto Shippuden 183.mkv
2017-03-29 14:26:43 INFO POSTPROCESSOR-AUTO :: Processing /TVdownloads/Naruto Shippuden 183.mkv (None)
2017-03-29 14:26:42 DEBUG POSTPROCESSOR-AUTO :: Parsed Naruto Shippuden 183.mkv into Naruto Shippuden - S04E12 [ABS: [83]] [ANIME VER: -1] [ABD: False] [ANIME: True] [whichReg: [u'bare']]
2017-03-29 14:26:42 DEBUG POSTPROCESSOR-AUTO :: Converted parsed result Naruto Shippuden 183 into Naruto Shippuden - S04E12 [ABS: [83]] [ANIME VER: -1] [ABD: False] [ANIME: True] [whichReg: [u'bare']]
2017-03-29 14:26:42 DEBUG POSTPROCESSOR-AUTO :: Found absolute number 83 for show Naruto Shippuden S04E12
2017-03-29 14:26:37 DEBUG POSTPROCESSOR-AUTO :: Processing folder /TVdownloads
2017-03-29 14:26:37 INFO POSTPROCESSOR-AUTO :: Processing /TVdownloads
2017-03-29 14:26:37 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /TVdownloads
2017-03-29 14:26:37 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /TVdownloads
2017-03-29 14:26:32 INFO POSTPROCESSOR :: Auto post processing task for /TVdownloads was added to the queue
2017-03-29 14:26:32 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
```

Also E200 is being detected as S2xE00.

```
2017-03-29 14:15:08 DEBUG POSTPROCESSOR-AUTO :: Moving file from /TVdownloads/Naruto.Shippuden.200.mkv to /Anime/Naruto Shippuden/Season 02/Naruto Shippuden - 2x00 -.mkv
2017-03-29 14:15:07 DEBUG POSTPROCESSOR-AUTO :: Checking if the path /Anime/Naruto Shippuden/Season 02 already exists
2017-03-29 14:15:07 DEBUG POSTPROCESSOR-AUTO :: Destination folder for this episode: /Anime/Naruto Shippuden/Season 02
2017-03-29 14:15:07 DEBUG POSTPROCESSOR-AUTO :: formatting pattern: Season %0S -> Season 02
2017-03-29 14:15:07 DEBUG POSTPROCESSOR-AUTO :: Using cached parse result for: Naruto.Shippuden.200
2017-03-29 14:15:06 DEBUG POSTPROCESSOR-AUTO :: Parsed /Anime/Naruto Shippuden/Season 02/Naruto Shippuden - 2x00 - into Season - S02E00 [ABD: False] [ANIME: False] [whichReg: [u'anime SxEE', u'anime_bare']]
2017-03-29 14:15:06 DEBUG POSTPROCESSOR-AUTO :: formatting pattern: %SN - %Sx%0E - %EN -> Naruto Shippuden - 2x00 -
2017-03-29 14:15:06 DEBUG POSTPROCESSOR-AUTO :: Using cached parse result for: Naruto.Shippuden.200
2017-03-29 14:15:05 DEBUG POSTPROCESSOR-AUTO :: Parsed /Anime/Naruto Shippuden/Season 02/Naruto Shippuden - 2x00 - into Season - S02E00 [ABD: False] [ANIME: False] [whichReg: [u'anime SxEE', u'anime_bare']]
2017-03-29 14:15:02 DEBUG POSTPROCESSOR-AUTO :: Folder name (TVdownloads) appears to be a valid release name. Using it.
2017-03-29 14:14:56 DEBUG POSTPROCESSOR-AUTO :: Using original release name Naruto.Shippuden.200.mkv
2017-03-29 14:14:56 INFO POSTPROCESSOR-AUTO :: Trying to clean any empty folders under /Anime/Naruto Shippuden/Season 02
2017-03-29 14:14:56 DEBUG POSTPROCESSOR-AUTO :: No associated files for /Anime/Naruto Shippuden/Season 02/Naruto Shippuden - 2x00 -.mkv were found during this pass
2017-03-29 14:14:56 INFO POSTPROCESSOR-AUTO :: Process method is 'move' and src and destination are on the same device, skipping free space check
2017-03-29 14:14:56 DEBUG POSTPROCESSOR-AUTO :: Trying to determine free space on destination drive
2017-03-29 14:14:53 DEBUG POSTPROCESSOR-AUTO :: File /Anime/Naruto Shippuden/Season 02/Naruto Shippuden - 2x00 -.mkv doesn't exist so there's no worries about replacing it
2017-03-29 14:14:53 DEBUG POSTPROCESSOR-AUTO :: Is ep a priority download: False
2017-03-29 14:14:53 DEBUG POSTPROCESSOR-AUTO :: Quality of the episode we're processing: SDTV
2017-03-29 14:14:53 DEBUG POSTPROCESSOR-AUTO :: Naruto.Shippuden.200.mkv looks like it has quality SDTV, using that
2017-03-29 14:14:53 DEBUG POSTPROCESSOR-AUTO :: Guessing quality for name Naruto.Shippuden.200.mkv, got SDTV
2017-03-29 14:14:52 DEBUG POSTPROCESSOR-AUTO :: Looking up quality for name Naruto.Shippuden.200.mkv, got Unknown
2017-03-29 14:14:52 DEBUG POSTPROCESSOR-AUTO :: Looking up quality for name TVdownloads, got Unknown
2017-03-29 14:14:52 DEBUG POSTPROCESSOR-AUTO :: Retrieving episode object for 2x0
2017-03-29 14:14:52 DEBUG POSTPROCESSOR-AUTO :: Parse result(release_group): None
2017-03-29 14:14:52 DEBUG POSTPROCESSOR-AUTO :: or Parse result(air_date): None
2017-03-29 14:14:52 DEBUG POSTPROCESSOR-AUTO :: Parse result(episode_numbers): [0]
2017-03-29 14:14:52 DEBUG POSTPROCESSOR-AUTO :: Parse result(season_number): 2
2017-03-29 14:14:52 DEBUG POSTPROCESSOR-AUTO :: Parse result(series_name): Naruto Shippuden
2017-03-29 14:14:52 DEBUG POSTPROCESSOR-AUTO :: Parse result not sufficient (all following have to be set). will not save release name
2017-03-29 14:14:51 DEBUG POSTPROCESSOR-AUTO :: Parsed Naruto.Shippuden.200 into Naruto Shippuden - S02E00 [ABD: False] [ANIME: False] [whichReg: [u'bare']]
2017-03-29 14:14:51 DEBUG POSTPROCESSOR-AUTO :: Converted parsed result Naruto.Shippuden.200 into Naruto Shippuden - S02E00 [ABD: False] [ANIME: False] [whichReg: [u'bare']]
2017-03-29 14:14:46 DEBUG POSTPROCESSOR-AUTO :: Analyzing name Naruto.Shippuden.200.mkv
2017-03-29 14:14:44 INFO POSTPROCESSOR-AUTO :: Processing /TVdownloads/Naruto.Shippuden.200.mkv (None)
2017-03-29 14:14:39 DEBUG POSTPROCESSOR-AUTO :: Parsed Naruto.Shippuden.200.mkv into Naruto Shippuden - S02E00 [ABD: False] [ANIME: False] [whichReg: [u'bare']]
2017-03-29 14:14:39 DEBUG POSTPROCESSOR-AUTO :: Converted parsed result Naruto.Shippuden.200 into Naruto Shippuden - S02E00 [ABD: False] [ANIME: False] [whichReg: [u'bare']]
2017-03-29 14:14:29 DEBUG POSTPROCESSOR-AUTO :: Processing folder /TVdownloads
2017-03-29 14:14:29 INFO POSTPROCESSOR-AUTO :: Processing /TVdownloads
2017-03-29 14:14:29 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /TVdownloads
2017-03-29 14:14:28 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /TVdownloads
2017-03-29 14:14:25 INFO POSTPROCESSOR :: Auto post processing task for /TVdownloads was added to the queue
2017-03-29 14:14:25 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
```

**Comment by h3llrais3r** [comment] 2017-04-04 17:32
Please enable the 'use_scene_numbering' option together with the 'anime' option.
I have a lot of anime in my list and I always use both options.
With this you should have better matching.

**Comment by h3llrais3r** [comment] 2017-04-04 17:40
Ok, tried it out myself and the problem is related to the file name.
`Naruto.Shippuden.200.mkv` does not match any anime regex.
There is a fallback to the anime_bare regex which think 183 means s1e83...
Did you rename the file before trying to process it?
Because the filename is not a valid anime scene name...

**Comment by h3llrais3r** [comment] 2017-04-04 18:22
I'll close this issue, since we can't support all types of file name patterns.
And in this case it's logic that it uses the bare regex because it has a higher score than anime_bare.
Only by using the correct naming pattern (but normally the anime should be provided in a correct scene name, why in this case I think it was either renamed manually or it was not really released by the scene) you will get a correct parsing.

**Closed by h3llrais3r** 2017-04-04 18:22 UTC

**Comment by alucarddelta** [comment] 2017-04-05 12:16
@h3llrais3r I ripped these episodes my self from my personal DVD collection using makeMKV and handbrake. So I named them accordingly to what SR page said 

> check if the show is Anime and episodes are released as Show.265 rather than Show.S02E03

 thinking it would just be that simple. So to answer your question, No as the file did not exist.

Adding [SDTV] (closest quality as DVD's aren't 720p) to the end did seem to correct the issue as you suggested. Its annoying fix but much better than renaming all the ep numbers to the index.

**Comment by h3llrais3r** [comment] 2017-04-05 16:30
That's just for indicating that you should indeed have shows with absolute number instead of SxxExx numbering. But you still need more info in the file name to have a better matching.
So since you did the rip yourself, you can indeed easily add the format to it (SDTV or SDDVD) to get it correctly processed.
