### ISSUE TITLE
[BTN] :: Unknown error while accessing provider. Error: No JSON object could be decoded 

### ISSUE THREAD

**Issue by gotoman00** [SickRage/SickRage#3179] opened 2017-02-19 16:46 UTC
Regular log:
2017-02-19 11:42:06 SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: Unknown error while accessing provider. Error: No JSON object could be decoded 

Debug logs:

2017-02-19 11:42:06 DEBUG SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: No data returned from provider
2017-02-19 11:42:06 WARNING SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: Unknown error while accessing provider. Error: No JSON object could be decoded 
2017-02-19 11:42:05 DEBUG SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: Search string: {'category': 'Episode', 'tvdb': 281403, 'name': u'S01E08'}
2017-02-19 11:42:05 DEBUG SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: No data returned from provider
2017-02-19 11:42:05 WARNING SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: Unknown error while accessing provider. Error: No JSON object could be decoded 
2017-02-19 11:42:04 DEBUG SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: Search string: {'category': 'Episode', 'tvdb': 281403, 'name': u'S01E07'}
2017-02-19 11:42:04 DEBUG SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: No data returned from provider
2017-02-19 11:42:04 WARNING SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: Unknown error while accessing provider. Error: No JSON object could be decoded 
2017-02-19 11:42:04 DEBUG SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: Search string: {'category': 'Episode', 'tvdb': 281403, 'name': u'S01E06'}
2017-02-19 11:42:04 DEBUG SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: No data returned from provider
2017-02-19 11:42:04 WARNING SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: Unknown error while accessing provider. Error: No JSON object could be decoded 
2017-02-19 11:42:03 DEBUG SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: Search string: {'category': 'Episode', 'tvdb': 281403, 'name': u'S01E05'}
2017-02-19 11:42:03 DEBUG SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: No data returned from provider
2017-02-19 11:42:03 WARNING SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: Unknown error while accessing provider. Error: No JSON object could be decoded 
2017-02-19 11:42:03 DEBUG SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: Search string: {'category': 'Episode', 'tvdb': 281403, 'name': u'S01E04'}
2017-02-19 11:42:03 DEBUG SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: No data returned from provider
2017-02-19 11:42:03 WARNING SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: Unknown error while accessing provider. Error: No JSON object could be decoded 
2017-02-19 11:42:02 DEBUG SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: Search string: {'category': 'Episode', 'tvdb': 281403, 'name': u'S01E03'}
2017-02-19 11:42:02 DEBUG SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: No data returned from provider
2017-02-19 11:42:02 WARNING SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: Unknown error while accessing provider. Error: No JSON object could be decoded 
2017-02-19 11:42:02 DEBUG SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: Search string: {'category': 'Episode', 'tvdb': 281403, 'name': u'S01E02'}
2017-02-19 11:42:02 DEBUG SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: No data returned from provider
2017-02-19 11:42:02 WARNING SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: Unknown error while accessing provider. Error: No JSON object could be decoded 
2017-02-19 11:42:01 DEBUG SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: Search string: {'category': 'Episode', 'tvdb': 281403, 'name': u'S01E01'}
2017-02-19 11:42:01 INFO SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: Performing episode search for F*ck, That's Delicious
2017-02-19 11:42:01 DEBUG SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: Fallback episode search initiated
2017-02-19 11:42:01 DEBUG SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: No data returned from provider
2017-02-19 11:42:01 WARNING SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: Unknown error while accessing provider. Error: No JSON object could be decoded 
2017-02-19 11:42:00 DEBUG SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: Search string: {'category': 'Season', 'tvdb': 281403, 'name': 'Season 1'}
2017-02-19 11:42:00 INFO SEARCHQUEUE-BACKLOG-281403 :: [BTN] :: Performing season pack search for F*ck, That's Delicious

**Comment by SickRage2** [comment] 2017-02-19 16:46
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [ ] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sharkykh** [comment] 2017-02-19 17:28
Duplicate of #3156 
#3177 will fix this issue soon.

**Closed by sharkykh** 2017-02-19 17:28 UTC
Labels: Duplicate
