### ISSUE TITLE
Empty folders no longer get deleted

### ISSUE THREAD

**Issue by rEes9P** [SickRage/SickRage#3206] opened 2017-02-23 12:40 UTC
Branch/Commit: master/59ce8253f9f43c2297ea4e558373d46c6e2b185b
OS: OS X 10.11.6
What you did: Post-processed episodes through NZBtoMedia and also manually
What happened: Post-processing works fine but empty folders remain and do not get deleted.
What you expected: I expected the empty folders to be deleted, as they always have been. I haven't changed any settings and "Don't delete empty folders" is and has always been unchecked. Everything worked fine before and the latest commit seems to have broken something.

Here's a log of a manual post-process request. The "Some.Show.S01E02.Some.Episode.DVDRip.XviD" folder remains intact. Earlier it would have been deleted. The same is true of auto-processing too.

Logs:

> Processing folder /Users/abc/Downloads/complete/Some.Show.S01E02.Some.Episode.DVDRip.XviD
Processing folder /Users/abc/Downloads/complete/Some.Show.S01E02.Some.Episode.DVDRip.XviD
Found unwanted files: ['.DS_Store']
Processing /Users/abc/Downloads/complete/Some.Show.S01E02.Some.Episode.DVDRip.XviD/Some.Show.S01E02.Some.Episode.DVDRip.XviD.avi (None)
Retrieving episode object for 1x2
Snatch history had a quality in it, using that: SD DVD
Is ep a priority download: False
File /Users/abc/Downloads/SickRage/Some Show/Season 1/1x02 - Some Episode.avi doesn't exist so there's no worries about replacing it
No associated files for /Users/abc/Downloads/SickRage/Some Show/Season 1/1x02 - Some Episode.avi were found during this pass
Found release name Some.Show.S01E02.Some.Episode.DVDRip.XviD
Destination folder for this episode: /Users/abc/Downloads/SickRage/Some Show/Season 1
No associated files for /Users/abc/Downloads/complete/Some.Show.S01E02.Some.Episode.DVDRip.XviD/Some.Show.S01E02.Some.Episode.DVDRip.XviD.avi were found during this pass
Moving file from /Users/abc/Downloads/complete/Some.Show.S01E02.Some.Episode.DVDRip.XviD/Some.Show.S01E02.Some.Episode.DVDRip.XviD.avi to /Users/abc/Downloads/SickRage/Some Show/Season 1/1x02 - Some Episode.avi
Processing succeeded for /Users/abc/Downloads/complete/Some.Show.S01E02.Some.Episode.DVDRip.XviD/Some.Show.S01E02.Some.Episode.DVDRip.XviD.avi
Deleting file: .DS_Store
Successfully processed

**Comment by SickRage2** [comment] 2017-02-23 12:40
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sharkykh** [comment] 2017-02-23 13:08
Just to make sure - only the empty directory remains - all of the files inside the directory have either been moved (processed or associated files), or deleted.
Correct?

**Comment by sharkykh** [comment] 2017-02-23 14:16
I was able to reproduce when an archive is unpacked in TV Downloads directory.
Will push a fix and open a PR momentarily.

**Comment by miigotu** [comment] 2017-02-23 14:38
Fixed in develop. Will be merged in to master by the weekend.

**Closed by miigotu** 2017-02-23 14:38 UTC
Labels: Bug / Issue, Confirmed, Fixed
