### ISSUE TITLE
nzbtomedia issues

### ISSUE THREAD

**Issue by Firetv344** [SickRage/SickRage#2865] opened 2017-01-09 02:23 UTC
Sickrage is snatching my files.....sending it to sabnzbd.....it download fine but sickrage don't auto process the file and it is still mark as snatch in sickrage history.....when i view my logs it says auto processing complete, but there's no file..
Manual processing works fine..
This was working fine...i didnt touch or  change anything..
Branch:Master
Commit: e33c7a9ba8cc888355b43b9118857a5cb366807b

[18:46:12] [INFO]::MAIN: Loading config from [/usr/local/share/nzbToMedia/autoProcessMedia.cfg]
[18:46:12] [INFO]::MAIN: Checking database structure...
[18:46:12] [INFO]::MAIN: Checking if git needs an update
[18:46:14] [INFO]::MAIN: There is a newer version available  (you're 174 commits behind)
[18:46:14] [INFO]::MAIN: nzbToMedia Version:3e4861e87c543a4d2debd8997feb16bda3ef5339 Branch:master (FreeBSD 10.3-RELEASE)
[18:46:14] [INFO]::MAIN: #########################################################
[18:46:14] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[18:46:14] [INFO]::MAIN: #########################################################
[18:46:14] [INFO]::MAIN: Script triggered from SABnzbd
[18:46:14] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[18:46:14] [INFO]::MAIN: Calling SickBeard:tv to post-process:Humans.S02E06.1080p.WEB-DL.DD5.1.H264-HMNS.nzb
[18:46:14] [INFO]::MAIN: Attempting to auto-detect tv fork
[18:46:14] [INFO]::MAIN: SickBeard:tv fork auto-detection successful ...
[18:46:14] [INFO]::MAIN: SickBeard:tv fork set to sickragetv
[18:46:14] [INFO]::MAIN: FLATTEN: Flattening directory: /mnt/media/downloads/sabnzbd/complete/tv/Humans.S02E06.1080p.WEB-DL.DD5.1.H264-HMNS
[18:46:15] [INFO]::TRANSCODER: Checking [Humans.S02E06.1080p.WEB-DL.DD5.1.H264-HMNS.mkv] for corruption, please stand by ...
[18:46:15] [INFO]::TRANSCODER: SUCCESS: [Humans.S02E06.1080p.WEB-DL.DD5.1.H264-HMNS.mkv] has no corruption.
[18:46:15] [POSTPROCESS]::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
[18:46:15] [POSTPROCESS]::SICKBEARD: Auto post processing task for /mnt/media/downloads/sabnzbd/complete/tv/Humans.S02E06.1080p.WEB-DL.DD5.1.H264-HMNS was added to the queue
[18:46:15] [POSTPROCESS]::SICKBEARD: <br\><span class='hidden'>Processing succeeded</span>
[18:46:15] [INFO]::CLEANDIR: Doing Forceful Clean of /mnt/media/downloads/sabnzbd/complete/tv/Humans.S02E06.1080p.WEB-DL.DD5.1.H264-HMNS
[18:46:15] [INFO]::MAIN: Deleting /mnt/media/downloads/sabnzbd/complete/tv/Humans.S02E06.1080p.WEB-DL.DD5.1.H264-HMNS
[18:46:15] [INFO]::MAIN: The /usr/local/share/nzbToMedia/nzbToSickBeard.py script completed successfully.
SickBeard: Successfully post-processed Humans.S02E06.1080p.WEB-DL.DD5.1.H264-HMNS.nzb!

**Comment by SickRage2** [comment] 2017-01-09 02:23
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by salsacalienemuy** [comment] 2017-01-09 04:24
You are not alone on this issue. Me, and a friend of mine are both experiencing this issue after updating to newer commits this morning.

**Comment by Firetv344** [comment] 2017-01-09 04:27
That's sort of good news....though I mess something up😊

**Comment by heymoe** [comment] 2017-01-09 04:50
The recent changes to Sickrage has somewhat broken nzbToMedia. Sickrage did somewhat roll back temporarily the change so nzbToMedia can update their code to support the new Sickrage changes but it still caused thing to fail to get post-processed if you have the force_clean option in nzbToMedia set to 1.
After setting that option to 0 things started to get processed again but you have to manually clean up any leftover files in your PP directory. The links below for more details. 

https://github.com/SickRage/SickRage/issues/2852
https://github.com/clinton-hall/nzbToMedia/issues/1158

**Comment by Firetv344** [comment] 2017-01-09 05:04
I see....that's gonna be a pain....any time frame on a fix..

**Comment by miigotu** [comment] 2017-01-09 05:05
https://github.com/clinton-hall/nzbToMedia/issues/1158#issuecomment-271211918

**Comment by Firetv344** [comment] 2017-01-09 05:10
Will setting force_clean to 0 delete left over files?

**Comment by miigotu** [comment] 2017-01-09 05:12
SickRage deletes the files. It has for ages.

**Comment by Firetv344** [comment] 2017-01-09 05:13
Ok...thank you

**Comment by heymoe** [comment] 2017-01-09 05:18
I set force_clean=0 and it's not cleaning up / deleting the left over files after SR PP the dir.

**Comment by Firetv344** [comment] 2017-01-09 05:26
So it's not cleaning up.....will there be a fix....or this is my only option...

**Comment by heymoe** [comment] 2017-01-09 05:31
Maybe I don't have a option enable or something. All I know when I ran force_clean=1, SR would do the snatch, nzbToMedia would call back to SR to tell it to do the PP but it seemed that nzbToMedia deleted the files before SR got to them so the SR logs said PP completed but nothing was done so the item was still listed as snatched.

Setting force_clean=0 got SR to PP the files but none of the leftover files are being cleaned so I have to go in and delete them manually right now.

Like I said, maybe I need to enable another option in SR or nzbToMedia but haven't found it.

**Comment by Firetv344** [comment] 2017-01-09 05:53
I can confirm...it's not cleaning leftover files...

**Comment by miigotu** [comment] 2017-01-09 07:57
On the post processing page make sure `delete associated files` and `delete rar caontents` are checked.
@heymoe since it says manual search in your logs then you havent updated to the latest SR version.

**Comment by Firetv344** [comment] 2017-01-09 12:09
Thank you.....is this a permanent fix or it will change..

**Comment by heymoe** [comment] 2017-01-09 13:12
Help & Info says I'm running the latest code:

Branch: master
Commit: e33c7a9ba8cc888355b43b9118857a5cb366807b

I didn't have those two options checked but they are now. I've also restart SR just to be safe. We will see if that fixes it the next time something gets PP.

**Comment by miigotu** [comment] 2017-01-09 17:28
Well, I have a way I can make it lock and return the result of the task, but if there is another task running the request has to wait for the current one to finish before it will run. Doing such a thing will make it just as if I never changed anything, I'm just not sure if thats the path I should take just yet.

**Comment by Firetv344** [comment] 2017-01-09 18:06
Whatever you think will make the process smoother..

**Comment by heymoe** [comment] 2017-01-09 18:20
I've been playing with Sonarr and it looks like it sends the snatch to the down-loader and then it checks in with the down-loader to see if the snatch is ready (as in finished downloaded and where the files are) to be PP or not. Instead of having nzbToMedia connect back to the SR from the down-loader to tell SR the download is ready to be PP. Maybe a option?

**Comment by miigotu** [comment] 2017-01-09 19:31
thats the goal, but im still in the process of rewriting the post processor to clean up the mess of patch on patch pn patch

**Comment by miigotu** [comment] 2017-01-10 06:55
#2870 adds a param `force_next` to make SR return the task result to nzbtomedia until the pp is rewritten over the next year. Please wait until clinton can add the param to nzbtomedia and we can test it and merge to master.

**Comment by miigotu** [comment] 2017-01-10 09:59
Fixed in sickrage master and nzbToMedia nightly

**Comment by miigotu** [comment] 2017-01-10 09:59
Leaving open for info

**Comment by Firetv344** [comment] 2017-01-10 14:27
That's good news...so should I leave force_clean at 0 or set everything back the way it was

**Comment by miigotu** [comment] 2017-01-10 15:47
everything can go back to how it was

**Comment by Firetv344** [comment] 2017-01-10 15:57
Ok....thank you very much..

**Comment by salsacalienemuy** [comment] 2017-01-10 20:11
I returned force_clean=0 after the update and the problem is still in effect. If sickrage snatches an episode after running sabtosickbeard all files are deleted, and the episode stays in snatched status. Also if a down load fails, and the script runs, it doesn't log it and try to download another nzb.

**Comment by Firetv344** [comment] 2017-01-10 20:15
Sad to say.....I'm experiencing the same thing after checking just now....the issue still exists..

**Comment by heymoe** [comment] 2017-01-10 20:21
Did you all upgrade to the nightly branch of nzbToMedia?

**Comment by Firetv344** [comment] 2017-01-10 20:22
Don't think I did.....how do I update it?

**Comment by heymoe** [comment] 2017-01-10 20:25
Depends on how you installed it. If you did a git clone then just change to the nightly branch:

git checkout nightly

If you downloaded it and just unzip the files then download the nightly zip:

https://github.com/clinton-hall/nzbToMedia/tree/nightly

**Comment by salsacalienemuy** [comment] 2017-01-10 20:36
Thanks for the tip I'll try it as soon as I can.

**Comment by heymoe** [comment] 2017-01-10 20:47
I just updated mine. I Just have to wait for something to get downloaded now.

**Comment by Firetv344** [comment] 2017-01-10 21:08
Updated to nzbtomedia nightly....it works like a charm😊

**Comment by salsacalienemuy** [comment] 2017-01-11 03:07
I updated it as well and everything is working perfectly.

**Comment by heymoe** [comment] 2017-01-11 04:10
Ditto. Looks good on my end too. Thanks!

**Comment by miigotu** [comment] 2017-01-11 04:49
Update to nzbToMedia nightly branch and latest SR.  pseudo help on changing to nightly nzbToMedia: https://github.com/SickRage/SickRage/issues/2865#issuecomment-271687800

All options can go back as they were before this fiasco

**Closed** 2017-03-19 01:45 UTC
Labels: Fixed
