### ISSUE TITLE
Can't Open Sickrage

### ISSUE THREAD

**Issue by jenwill05** [SickRage/SickRage#3607] opened 2017-04-07 13:39 UTC
Using Windows 10

Computer went belly up so had to get new hard drive and operating system. Now I am trying to re-download Sickrage. It installs fine, but when I go to open I get that it Will Not Connection.

Tried running a git pull like other posts say but it is still not doing anything. 
Not sure if I did it correctly. Any help would be appreciated.

**Comment by sharkykh** [comment] 2017-04-07 15:29
Look for the logs in your data folder and post them using http://pastebin.com

**Comment by DarkDivide** [comment] 2017-04-07 19:25
Unfortunately, i have also reinstalled Windows 10 and am having the same issue. 

Looks like Nssm.exe starts ok and i can see in Task manager, but i cant find the site localhost:8081. Installed All Defaults, nothing special.

Looking in the Data Folder, there are no files / folders.

Only Log i can find is C:\Sickrage\Sickrage\.git\logs\HEAD

0000000000000000000000000000000000000000 4b3dad8eec3e238b1cadc809acf8e0e26deb9eb3 unknown <DD@Host.(none)> 1491587831 +0100	clone: from https://github.com/SickRage/SickRage.git

**Comment by sharkykh** [comment] 2017-04-07 19:38
What is your windows build?
Also, try stopping the SickRage service (with nssm) and running from cmd:
```
C:\SickRage\Python\python.exe C:\SickRage\SickRage\SickBeard.py --datadir=C:\SickRage\Data
```
And post the output.

**Comment by DarkDivide** [comment] 2017-04-07 19:41
Windows 10 Version 1703, OS Build 15063.13

Looks like that command did the trick. As it has now resolved a webpage.

Output:
C:\Windows\system32>C:\SickRage\Python\python.exe C:\SickRage\SickRage\SickBeard.py --datadir=C:\SickRage\Data
Unable to find C:\SickRage\Data\config.ini, all settings will be default!
20:39:37 INFO::MAIN :: Backing up database before upgrade
20:39:37 INFO::MAIN :: Proceeding with upgrade
20:39:37 INFO::MAIN :: Add minor version numbers to database
20:39:37 INFO::MAIN :: Updated to: 43.1
20:39:37 INFO::MAIN :: Backing up database before upgrade
20:39:37 INFO::MAIN :: Proceeding with upgrade
20:39:38 ERROR::MAIN :: git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
None
20:39:38 WARNING::MAIN :: No git specified, can't use git commands
20:39:38 INFO::MAIN :: Starting SickRage [] using 'C:\SickRage\Data\config.ini'
20:39:38 INFO::MAIN :: Generating New API key
20:39:38 INFO::TORNADO :: Starting SickRage on http://0.0.0.0:8081/
20:39:38 INFO::MAIN :: Checking for scene exception updates from http://sickrage.github.io/scene_exceptions/scene_exceptions.json
20:39:38 INFO::CHECKVERSION :: Checking for updates using GIT
20:39:38 WARNING::CHECKVERSION :: No git specified, can't use git commands
20:39:38 WARNING::CHECKVERSION :: No git specified, can't use git commands
20:39:38 INFO::MAIN :: Checking for XEM scene exception updates for theTVDB
20:39:39 INFO::MAIN :: Checking for scene exception updates for AniDB

**Comment by sharkykh** [comment] 2017-04-07 19:48
Judging from your Windows build, I would say you're experiencing the same issue as described in #3070.
Close the console window and try running with nssm again, then go to Services, look for SickRage and check the service status.
If it's paused, it's the same issue.

We don't support Windows builds which aren't officially released yet (like Insider builds, Creators Update, etc.)

**Comment by DarkDivide** [comment] 2017-04-07 19:50
That is correct, it is showing as Paused.

I am not using anything special that i know of. I have done a Vanilla Windows 10 Install and installed all Windows Updates?

**Comment by sharkykh** [comment] 2017-04-07 19:57
Then, I guess Creators Update **is** official.
This is not an issue with SickRage.
It's a bug with Windows, I think it has something to do with Python and services but I didn't really participate in the conversation on #3070.
Unfortunately, we have no solution for it at the moment.

**Comment by DarkDivide** [comment] 2017-04-07 20:00
Well that is frustrating, i would be prepared for a lot more reports if Windows updates are breaking things.

I appreciate you taking the time to investigate.

**Comment by sharkykh** [comment] 2017-04-07 20:02
That being said...

Looks like nssm got updated to support Creators Update, **_maybe_** that will help.

Go to `C:\SickRage\Installer` and rename `nssm.exe` to `nssm.old.exe`.
Download [this](https://nssm.cc/release/nssm-2.24.zip) and unpack it. Put the extracted `nssm.exe` in that folder and try running SR again.

**Comment by sharkykh** [comment] 2017-04-07 20:06
Sorry, my bad
Download this https://nssm.cc/ci/nssm-2.24-87-g203bfae.zip
(Pre release)

**Comment by DarkDivide** [comment] 2017-04-07 20:09
No luck i'm afraid, it still enters a paused state.

**Comment by sharkykh** [comment] 2017-04-07 20:13
So it is still a Windows bug, sorry.
You can Google "uninstalling Creators Update" as this is the cause for the issue.

**Comment by DarkDivide** [comment] 2017-04-07 20:21
I thought i'd give this a try, i restored my pre-installed configuration (Data folder) and using the command you provided: C:\SickRage\Python\python.exe C:\SickRage\SickRage\SickBeard.py --datadir=C:\SickRage\Data --port=8081

It has loaded up my previous configuration - an error about not being able to find my git Executable.

So i've installed Git for Windows and pointed the config to it and it seems to be working alright.

This isn't ideal, but if it works in the interim until things get fixed i can live with it.

**Comment by sharkykh** [comment] 2017-04-07 20:28
:+1:

**Comment by sharkykh** [comment] 2017-04-07 20:32
I'll close this mainly because there's already an issue open about this.

**Comment by jenwill05** [comment] 2017-04-07 20:46
I'm sorry but I am not that programming knowledgeable so I am not sure I follow the instructions and I dont think it is the same issue as others are having. 

I dont have a way restore anything because everything was lost when we lost our hard drive. 

So are you saying the reason we cant get in is due to Windows and not Sickrage?

What steps do I take to even get to a screen where I can log into my Sickrage?

**Comment by sharkykh** [comment] 2017-04-07 20:51
Whoa, my apologies. I'm on mobile and the avatars looked very similar so I didn't notice I was chatting with a different user.

Please try to run SickRage manually using 
`C:\SickRage\Python\python.exe C:\SickRage\SickRage\SickBeard.py --datadir=C:\SickRage\Data --port=8081`

(If you installed SickRage to its default location)

**Comment by jenwill05** [comment] 2017-04-07 21:10
thank you. I will try that when I get home later tonight, I am currently at work so cant test at the moment. Thank you for your quick replay though. It is very appreciated.

**Comment by jenwill05** [comment] 2017-04-08 02:39
So i went to: C:\SickRage\Python\python.exe

Then in the Command Prompt i typed this in: 
C:\SickRage\SickRage\SickBeard.py --datadir=C:\SickRage\Data --port=8081

Then it gave the this:  SyntaxError: Invalid Syntax

**Comment by jenwill05** [comment] 2017-04-08 02:48
I also checked my Data Folder in C:/SickRage/Data and it is empty. Am I looking in the wrong place?

**Comment by sharkykh** [comment] 2017-04-08 16:08
You don't need to navigate to any folders with the command I gave you,
simply open cmd, and use the command like it's written:
```
C:\SickRage\Python\python.exe C:\SickRage\SickRage\SickBeard.py --datadir=C:\SickRage\Data --port=8081
```

**Comment by jenwill05** [comment] 2017-04-08 16:48
oh my bad. Sorry I am not super experienced as you can tell.

I put that in and it ran. I can now get into SickRage!! Thank you!!

I am not getting this message:
Unable to find your git executable - Shutdown SickRage and EITHER set git_path in your config.ini OR delete your .git folder and run from source to enable updates.

Not sure if I need to do anything about this??

**Comment by sharkykh** [comment] 2017-04-08 17:00
Yes, **but this not a fix**.
I still think your issue is related to #3070 like I said. [Check your Windows build](https://www.howtogeek.com/236195/how-to-find-out-which-build-and-version-of-windows-10-you-have/).

In order to fix the message you're getting for now, go to General config, Advanced settings and set "Git executable path" to `C:\SickRage\Git\cmd\git.exe`

**Comment by jenwill05** [comment] 2017-04-08 17:25
After exiting Chrome, it no longer opens. 

Here is my Windows Build:
Edition: Windows 10 Home
Version: 1703
OD Build: 15063.13

**Comment by sharkykh** [comment] 2017-04-08 17:29
1. In order for SickRage to be running you **have to have** the run it using the command and keep the cmd (black) window open. If you close it, SickRage will shutdown.

2. I was right and this issue currently has no fix. We cannot fix this as this is an issue with Windows services.

**Comment by jenwill05** [comment] 2017-04-08 17:31
ok so I will keep the cmd up until there is a fix?

**Comment by sharkykh** [comment] 2017-04-08 18:07
I don't know how long that will be.
If you downgrade Windows and remove "Creators Update" (that's version 1703), SickRage should work out of the box.

You can try to use this guide.
http://www.thewindowsclub.com/rollback-uninstall-windows-10-creators-update
Remember to backup **all your important data!**

**Comment by sharkykh** [comment] 2017-04-08 18:13
Hold that thought,
 try this users' workaround:
https://github.com/SickRage/SickRage/issues/3070#issuecomment-292735744

**Closed** 2017-04-10 17:23 UTC
Labels: Duplicate

**Comment by jenwill05** [comment] 2017-04-25 23:06
So I have been using the prompt you provided and it has been working up until yesterday. Now I get an error saying: This app cant run on your pc. To find a version for your pc, check with you software publisher.

I went to do the fix you also provided but I am not sure how to get to the screens they are talking about now that I cant get into SickRage at all anymore. Any thoughts?

**Comment by sharkykh** [comment] 2017-04-28 11:01
Please explain what you mean by prompt? I'm not sure what you're referring to.

About the latest fix that seems to work for everyone that have the newer Windows 10 build,
Click Start and type in `Edit SickRage`, then click the search result (Edit SickRage Service)
You should get a UAC warning, click yes/ok, then a window like this should open: ![img](https://cloud.githubusercontent.com/assets/5970135/24831248/549330cc-1c5c-11e7-948b-329cde0fbad7.jpg)

Click the Process tab, deselect Console Window, save.
Then restart the SickRage service (Start > `Stop SickRage` > click result, THEN Start > `Start SickRage` > click result)
