### ISSUE TITLE
[APP SUBMITTED]: u'The.Graham.Norton.Show.S20E03.WEB.h264-ROFL'

### ISSUE THREAD

**Issue by Rouzax** [SickRage/SickRage#2975] opened 2017-01-25 15:08 UTC
### INFO
Python Version: **2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8.1-6.3.9600**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@a3ce318f2c3b207da474db4c8e3cf62bb9032e0e
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: [a3ce318] Exception while searching IPTorrents. Error: KeyError(u'The.Graham.Norton.Show.S20E03.WEB.h264-ROFL',)
```
LOG:
```
2017-01-25 08:09:54 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Parsed The.Graham.Norton.Show.S20E12.720p.HDTV.x264-FTP into The Graham Norton Show - S20E12 [GROUP: FTP] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2017-01-25 08:09:54 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Any,Best = [ 720p WEB-DL ] [ None ] Found = [ 720p HDTV ]
2017-01-25 08:09:54 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Don't want this quality, ignoring found result for The Graham Norton Show S20E12 with quality 720p HDTV
2017-01-25 08:09:54 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Ignoring result The.Graham.Norton.Show.S20E12.720p.HDTV.x264-FTP.
2017-01-25 08:09:54 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Converted parsed result The.Graham.Norton.Show.S20E13.REAL.720p.HDTV.X264-FTP into The Graham Norton Show - S20E13 [GROUP: FTP] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2017-01-25 08:09:54 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Parsed The.Graham.Norton.Show.S20E13.REAL.720p.HDTV.X264-FTP into The Graham Norton Show - S20E13 [GROUP: FTP] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2017-01-25 08:09:54 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Any,Best = [ 720p WEB-DL ] [ None ] Found = [ 720p HDTV ]
2017-01-25 08:09:54 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Don't want this quality, ignoring found result for The Graham Norton Show S20E13 with quality 720p HDTV
2017-01-25 08:09:54 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Ignoring result The.Graham.Norton.Show.S20E13.REAL.720p.HDTV.X264-FTP.
2017-01-25 08:09:54 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Converted parsed result The.Graham.Norton.Show.S20E13.720p.HDTV.x264-DEADPOOL into The Graham Norton Show - S20E13 [GROUP: DEADPOOL] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2017-01-25 08:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Parsed The.Graham.Norton.Show.S20E13.720p.HDTV.x264-DEADPOOL into The Graham Norton Show - S20E13 [GROUP: DEADPOOL] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2017-01-25 08:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Any,Best = [ 720p WEB-DL ] [ None ] Found = [ 720p HDTV ]
2017-01-25 08:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Don't want this quality, ignoring found result for The Graham Norton Show S20E13 with quality 720p HDTV
2017-01-25 08:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Ignoring result The.Graham.Norton.Show.S20E13.720p.HDTV.x264-DEADPOOL.
2017-01-25 08:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Converted parsed result The.Graham.Norton.Show.S20E02.Danny.Devito-Ewan.Mcgregor-Miranda.Hart-John.Bishop.480p.x264-mSD into The Graham Norton Show - S20E02 [GROUP: mSD] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2017-01-25 08:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Parsed The.Graham.Norton.Show.S20E02.Danny.Devito-Ewan.Mcgregor-Miranda.Hart-John.Bishop.480p.x264-mSD into The Graham Norton Show - S20E02 [GROUP: mSD] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2017-01-25 08:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Any,Best = [ 720p WEB-DL ] [ None ] Found = [ SDTV ]
2017-01-25 08:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Don't want this quality, ignoring found result for The Graham Norton Show S20E02 with quality SDTV
2017-01-25 08:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Ignoring result The.Graham.Norton.Show.S20E02.Danny.Devito-Ewan.Mcgregor-Miranda.Hart-John.Bishop.480p.x264-mSD.
2017-01-25 08:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Converted parsed result The.Graham.Norton.Show.S20E02.HDTV.x264.RBB into The Graham Norton Show - S20E02 [ABD: False] [ANIME: False] [whichReg: ['standard']]
2017-01-25 08:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Parsed The.Graham.Norton.Show.S20E02.HDTV.x264.RBB into The Graham Norton Show - S20E02 [ABD: False] [ANIME: False] [whichReg: ['standard']]
2017-01-25 08:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Any,Best = [ 720p WEB-DL ] [ None ] Found = [ SDTV ]
2017-01-25 08:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Don't want this quality, ignoring found result for The Graham Norton Show S20E02 with quality SDTV
2017-01-25 08:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Ignoring result The.Graham.Norton.Show.S20E02.HDTV.x264.RBB.
2017-01-25 08:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Converted parsed result The.Graham.Norton.Show.S20E03.480p.x264-mSD into The Graham Norton Show - S20E03 [GROUP: mSD] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2017-01-25 08:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Parsed The.Graham.Norton.Show.S20E03.480p.x264-mSD into The Graham Norton Show - S20E03 [GROUP: mSD] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2017-01-25 08:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Any,Best = [ 720p WEB-DL ] [ None ] Found = [ SDTV ]
2017-01-25 08:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Don't want this quality, ignoring found result for The Graham Norton Show S20E03 with quality SDTV
2017-01-25 08:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Ignoring result The.Graham.Norton.Show.S20E03.480p.x264-mSD.
2017-01-25 08:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Converted parsed result The.Graham.Norton.Show.S20E03.WEB.h264-ROFL into The Graham Norton Show - S20E03 [GROUP: ROFL] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2017-01-25 08:09:55 ERROR    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: [a3ce318] Exception while searching IPTorrents. Error: KeyError(u'The.Graham.Norton.Show.S20E03.WEB.h264-ROFL',)
Traceback (most recent call last):
  File "C:\GitHub\SickRage\sickbeard\search.py", line 479, in searchProviders
    searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
  File "C:\GitHub\SickRage\sickrage\providers\GenericProvider.py", line 180, in find_search_results
    parse_result = NameParser(parse_method=('normal', 'anime')[show.is_anime]).parse(title)
  File "C:\GitHub\SickRage\sickbeard\name_parser\parser.py", line 476, in parse
    name_parser_cache.add(name, final_result)
  File "C:\GitHub\SickRage\sickbeard\name_parser\parser.py", line 580, in add
    del self._previous_parsed[self._previous_parsed.keys()[0]]
KeyError: u'The.Graham.Norton.Show.S20E03.WEB.h264-ROFL'
2017-01-25 08:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [IPTorrents] :: Traceback (most recent call last):
  File "C:\GitHub\SickRage\sickbeard\search.py", line 479, in searchProviders
    searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
  File "C:\GitHub\SickRage\sickrage\providers\GenericProvider.py", line 180, in find_search_results
    parse_result = NameParser(parse_method=('normal', 'anime')[show.is_anime]).parse(title)
  File "C:\GitHub\SickRage\sickbeard\name_parser\parser.py", line 476, in parse
    name_parser_cache.add(name, final_result)
  File "C:\GitHub\SickRage\sickbeard\name_parser\parser.py", line 580, in add
    del self._previous_parsed[self._previous_parsed.keys()[0]]
KeyError: u'The.Graham.Norton.Show.S20E03.WEB.h264-ROFL'

2017-01-25 08:09:55 INFO     SEARCHQUEUE-BACKLOG-80660 :: [TorrentDay] :: Performing season pack search for The Graham Norton Show
2017-01-25 08:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [TorrentDay] :: Search Mode: Season
2017-01-25 08:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80660 :: [TorrentDay] :: Search string: The Graham Norton Show S20
```

---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment] 2017-01-25 15:08
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by Rouzax** [comment] 2017-01-25 15:12
looks to be the same as #2974 2974

**Comment by Rouzax** [comment] 2017-01-30 09:28
Had more of the same error see
#3044
#3045
#3046
#3047
#3048
#3049

**Comment by miigotu** [comment] 2017-01-30 10:47
Looks like it needs some thread locking. Not sure how you are making this happen though.

**Comment by Rouzax** [comment] 2017-01-30 11:21
I also have no clue 😀
Let me know if you need any more info or logs.

**Comment by miigotu** [comment] 2017-01-31 08:09
Please see if its fixed on develop. Not sure if you can reproduce it easily.

**Comment by Rouzax** [comment] 2017-01-31 12:35
Just switched to the develop branch. 
I'm unable to reproduce the error as I don't know what triggers it. Will keep it running for a couple of days and report back.

**Comment by Rouzax** [comment] 2017-02-01 07:57
So far there has not been a new error message. Will keep a eye on it.

**Comment by Rouzax** [comment] 2017-02-02 10:05
Still no errors in the Dev version

**Comment by miigotu** [comment] 2017-02-02 21:37
closing then =P

**Closed by miigotu** 2017-02-02 21:37 UTC
