### ISSUE TITLE
[APP SUBMITTED]: data must be a byte string

### ISSUE THREAD

**Issue by pilothaz** [SickRage/SickRage#2292] opened 2016-09-03 11:43 UTC
### INFO

Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4219585709dc1d9ed23ec7ea773a51e92c97b7b5
No Log available with ERRORS:
### ERROR

```
Thread-15 :: [4219585] Error Sending Slack message: data must be a byte string
```

---

_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment] 2016-09-03 11:43
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by pilothaz** [comment] 2016-09-03 11:43
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4219585709dc1d9ed23ec7ea773a51e92c97b7b5
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: [4219585] Error Sending Slack message: data must be a byte string
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by pilothaz** [comment] 2016-09-09 12:13
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@8564c29aa3b2d95bf41e03eed7e5a6938f1a6b3a
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: [8564c29] Error Sending Slack message: data must be a byte string
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by neoatomic** [comment] 2016-09-29 11:44
@forge33 Is this something you might be able to check.?

**Comment by forge33** [comment] 2016-09-29 14:00
for sure, I'll take a look later today

**Comment by forge33** [comment] 2016-09-29 14:13
@pilothaz do you have any additional information to help me debug this?

**Comment by pilothaz** [comment] 2016-10-01 02:26
Only thing i have noticed is that it gives that error message when it tries to send the notification.  It is odd when there is no issue with the test notification that you have within the settings.

**Comment by aondeto** [comment] 2016-10-10 05:19
I have the same problem here ...

**Comment by aondeto** [comment] 2016-10-10 05:23
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-STABLE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@6a023791556047f7ce04cd6b5185d41ed212bd84
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: [6a02379] Error Sending Slack message: data must be a byte string
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by aondeto** [comment] 2016-10-10 05:23
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-STABLE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@6a023791556047f7ce04cd6b5185d41ed212bd84
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-313937 :: [6a02379] Error Sending Slack message: data must be a byte string
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by aondeto** [comment] 2016-10-11 06:53
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@df31d0cec4d382c0e9c52550ab6ac7c682fef70e
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-247824 :: [df31d0c] Error Sending Slack message: data must be a byte string
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment] 2016-10-11 08:55
I think this is a python 2.7.9 bug. I cannot reproduce this error on 2.7.12

**Comment by pilothaz** [comment] 2016-10-11 17:03
@miigotu I did a pkg update/upgrade and did my FreeNAS jail for SickRage now has 2.7.12 for python but I do not see it within the help & info page as being the new one. 

Am I doing this incorrectly?

python27-2.7.12                Interpreted object-oriented programming language

**Comment by OppieTV** [comment] 2017-03-01 19:45
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-Debian-8**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@de056c2380cb140bf8430a1ac4569899b3b44a52
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-311892 :: [T411] :: [de056c2] Request failed: data must be a byte string
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by OppieTV** [comment] 2017-03-01 19:46
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-Debian-8**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@de056c2380cb140bf8430a1ac4569899b3b44a52
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-311892 :: [T411] :: [de056c2] Request failed: data must be a byte string
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by OppieTV** [comment] 2017-03-01 19:46
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-Debian-8**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@de056c2380cb140bf8430a1ac4569899b3b44a52
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-80379 :: [T411] :: [de056c2] Request failed: data must be a byte string
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by OppieTV** [comment] 2017-03-01 19:48
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-Debian-8**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@de056c2380cb140bf8430a1ac4569899b3b44a52
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-311892 :: [T411] :: [de056c2] Request failed: data must be a byte string
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment] 2017-03-01 19:49
@OppieTV I need log info to fix this...

**Comment by turak** [comment] 2017-03-01 22:32
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-8**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@de056c2380cb140bf8430a1ac4569899b3b44a52
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [T411] :: [de056c2] Request failed: data must be a byte string
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by turak** [comment] 2017-03-01 22:35
@miigotu wich log info you need please ?

**Comment by sharkykh** [comment] 2017-03-01 22:39
@turak [enable debugging](https://github.com/SickRage/SickRage/wiki/FAQ%27s-and-Fixes#how-do-i-enable-debug-logs-to-get-more-detailed-information-in-my-logs) and post your logs after this error happens again.

**Comment by turak** [comment] 2017-03-01 22:42
@sharkykh last comment updated. it's ok ?

**Comment by sharkykh** [comment] 2017-03-01 22:51
Yes thank you

**Comment by miigotu** [comment] 2017-03-01 23:07
I'll fix this when I get home

**Comment by bibi32** [comment] 2017-03-02 10:13
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-4.4.40-1-pve-x86_64-with-debian-8.7**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@26da4a8fcb8a783b5747a16e8736ba0224a5fc7e
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [T411] :: [26da4a8] Request failed: data must be a byte string
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by bibi32** [comment] 2017-03-02 21:50
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-4.4.40-1-pve-x86_64-with-debian-8.7**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@66babc76d28646807c1040a3e225072b410489ad
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [T411] :: [66babc7] Request failed: data must be a byte string
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by kriegalex** [comment] 2017-03-02 22:13
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-10.3-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@66babc76d28646807c1040a3e225072b410489ad
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-80379 :: [T411] :: [66babc7] Request failed: data must be a byte string
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Imprezz** [comment] 2017-03-03 08:45
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-8**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@66babc76d28646807c1040a3e225072b410489ad
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-320724 :: [T411] :: [66babc7] Request failed: data must be a byte string
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by PxReaz** [comment] 2017-03-03 13:06
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.7**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@66babc76d28646807c1040a3e225072b410489ad
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [T411] :: [66babc7] Request failed: data must be a byte string
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by turak** [comment] 2017-03-03 19:45
thanks a lot @miigotu 
Just need to wait it's merged with master or dev branch ? :)

**Comment by miigotu** [comment] 2017-03-03 19:59
Its in develop now. Please check that it works

**Comment by turak** [comment] 2017-03-03 20:09
```
➜  sickrage git:(develop) vi sickbeard/clients/generic.py
➜  sickrage git:(develop) git pull
Already up-to-date.
```

But i don't see change that you made on the commit :/
So, always same error 
(sorry for my bad english..)

**Comment by miigotu** [comment] 2017-03-03 20:56
```
12:55:34 INFO::SEARCHQUEUE-MANUAL-268592 :: [T411] :: Quality of The.100.S04E04.FASTSUB.VOSTFR.HDTV.XviD-NEWZT is SDTV
12:55:34 DEBUG::SEARCHQUEUE-MANUAL-268592 :: [T411] :: Picked The.100.S04E04.FASTSUB.VOSTFR.WEB-DL.x264-ARK01 as the best
12:55:34 DEBUG::SEARCHQUEUE-MANUAL-268592 :: [T411] :: Checking if we should keep searching after we've found The.100.S04E04.FASTSUB.VOSTFR.WEB-DL.x264-ARK01
12:55:34 INFO::SEARCHQUEUE-MANUAL-268592 :: Downloading The.100.S04E04.FASTSUB.VOSTFR.WEB-DL.x264-ARK01 from T411
12:55:34 DEBUG::SEARCHQUEUE-MANUAL-268592 :: GET URL: https://api.t411.li/torrents/download/5659048 [Status: 200]
12:55:35 DEBUG::SEARCHQUEUE-MANUAL-268592 :: Calling Transmission Client
12:55:35 DEBUG::SEARCHQUEUE-MANUAL-268592 :: Transmission: Requested a POST connection to url http://192.168.10.10:9091/************/rpc and data: {"arguments": {}, "method": "session-get"}
12:55:35 DEBUG::SEARCHQUEUE-MANUAL-268592 :: Transmission: Response to the POST request is {"arguments":{"alt-speed-down":50,"alt-speed-enabled":false,"alt-speed-time-begin":540,"alt-speed-time-day":127,"alt-speed-time-enabled":false,"alt-speed-time-end":1020,"alt-speed-up":50,"blocklist-enabled":false,"blocklist-size":0,"blocklist-url":"http://www.example.com/blocklist","cache-size-mb":8,"config-dir":"/var/lib/************-daemon/.config/************-daemon","dht-enabled":true,"download-dir":"/RAID1/Complete","download-dir-free-space":756396228608,"download-queue-enabled":false,"download-queue-size":5,"encryption":"preferred","idle-seeding-limit":30,"idle-seeding-limit-enabled":false,"incomplete-dir":"/RAID1/Incomplete","incomplete-dir-enabled":true,"lpd-enabled":false,"peer-limit-global":1000,"peer-limit-per-torrent":500,"peer-port":42236,"peer-port-random-on-start":false,"pex-enabled":true,"port-forwarding-enabled":false,"queue-stalled-enabled":true,"queue-stalled-minutes":30,"rename-partial-files":true,"rpc-version":15,"rpc-version-minimum":1,"script-torrent-done-enabled":false,"script-torrent-done-filename":"","seed-queue-enabled":false,"seed-queue-size":10,"seedRatioLimit":2,"seedRatioLimited":true,"speed-limit-down":100,"speed-limit-down-enabled":false,"speed-limit-up":100,"speed-limit-up-enabled":false,"start-added-torrents":true,"trash-original-torrent-files":false,"units":{"memory-bytes":1024,"memory-units":["KiB","MiB","GiB","TiB"],"size-bytes":1000,"size-units":["kB","MB","GB","TB"],"speed-bytes":1000,"speed-units":["kB/s","MB/s","GB/s","TB/s"]},"utp-enabled":true,"version":"2.84 (14307)"},"result":"success"}
```

**Comment by turak** [comment] 2017-03-03 21:10
Branch: develop
Commit: 3dcc66e4f5dd0993f419fa4428b111ef53267052
Version: v2017.03.02-1
Database Version: 44.0

Same commit on your side ?

**Comment by miigotu** [comment] 2017-03-03 21:14
Yes, did you restart Sickrage after pulling develop?
Need logs

**Comment by turak** [comment] 2017-03-03 21:20
yes restart done

```
2017-03-03 22:19:39 DEBUG    SEARCHQUEUE-MANUAL-268592 :: [T411] :: Search string: Les 100 S04E01
2017-03-03 22:19:39 ERROR    SEARCHQUEUE-MANUAL-268592 :: [T411] :: [3dcc66e] Request failed: data must be a byte string
Traceback (most recent call last):
  File "/home/rtorrent/sickrage/sickbeard/helpers.py", line 1465, in handle_requests_exception
    raise requests_exception
TypeError: data must be a byte string
2017-03-03 22:19:39 DEBUG    SEARCHQUEUE-MANUAL-268592 :: [T411] :: Traceback (most recent call last):
  File "/home/rtorrent/sickrage/sickbeard/helpers.py", line 1465, in handle_requests_exception
    raise requests_exception
TypeError: data must be a byte string

2017-03-03 22:19:39 ERROR    SEARCHQUEUE-MANUAL-268592 :: [T411] :: [3dcc66e] Request failed: data must be a byte string
Traceback (most recent call last):
  File "/home/rtorrent/sickrage/sickbeard/helpers.py", line 1465, in handle_requests_exception
    raise requests_exception
TypeError: data must be a byte string
2017-03-03 22:19:39 DEBUG    SEARCHQUEUE-MANUAL-268592 :: [T411] :: Traceback (most recent call last):
  File "/home/rtorrent/sickrage/sickbeard/helpers.py", line 1465, in handle_requests_exception
    raise requests_exception
TypeError: data must be a byte string

2017-03-03 22:19:39 ERROR    SEARCHQUEUE-MANUAL-268592 :: [T411] :: [3dcc66e] Request failed: data must be a byte string
Traceback (most recent call last):
  File "/home/rtorrent/sickrage/sickbeard/helpers.py", line 1465, in handle_requests_exception
    raise requests_exception
TypeError: data must be a byte string
2017-03-03 22:19:39 DEBUG    SEARCHQUEUE-MANUAL-268592 :: [T411] :: Traceback (most recent call last):
  File "/home/rtorrent/sickrage/sickbeard/helpers.py", line 1465, in handle_requests_exception
    raise requests_exception
TypeError: data must be a byte string

2017-03-03 22:19:39 ERROR    SEARCHQUEUE-MANUAL-268592 :: [T411] :: [3dcc66e] Request failed: data must be a byte string
Traceback (most recent call last):
  File "/home/rtorrent/sickrage/sickbeard/helpers.py", line 1465, in handle_requests_exception
    raise requests_exception
TypeError: data must be a byte string
2017-03-03 22:19:39 DEBUG    SEARCHQUEUE-MANUAL-268592 :: [T411] :: Traceback (most recent call last):
  File "/home/rtorrent/sickrage/sickbeard/helpers.py", line 1465, in handle_requests_exception
    raise requests_exception
TypeError: data must be a byte string

```

**Comment by miigotu** [comment] 2017-03-03 21:24
I'll change the show language and test with s04e01 shortly

**Comment by miigotu** [comment] 2017-03-03 21:49
```
13:48:41 DEBUG::SEARCHQUEUE-MANUAL-268592 :: [T411] :: Search Mode: Episode
13:48:41 DEBUG::SEARCHQUEUE-MANUAL-268592 :: [T411] :: Search string: Les 100 S04E01
13:48:41 DEBUG::SEARCHQUEUE-MANUAL-268592 :: [T411] :: GET URL: https://api.t411.li/torrents/search/Les%20100%20S04E01*?cid=433&limit=100 [Status: 200]
13:48:41 DEBUG::SEARCHQUEUE-MANUAL-268592 :: [T411] :: Data returned from provider does not contain any torrents
```

Try restarting the whole device

**Comment by miigotu** [comment] 2017-03-03 21:52
And with the english name:
```
13:51:34 DEBUG::SEARCHQUEUE-MANUAL-268592 :: [T411] :: Search string: The 100 S04E01
13:51:35 DEBUG::SEARCHQUEUE-MANUAL-268592 :: [T411] :: GET URL: https://api.t411.li/torrents/search/The%20100%20S04E01*?cid=433&limit=100 [Status: 200]
13:51:35 DEBUG::SEARCHQUEUE-MANUAL-268592 :: [T411] :: Found result: The.100.S04E01................... with 563 seeders and 2 leechers
13:51:35 DEBUG::SEARCHQUEUE-MANUAL-268592 :: [T411] :: Found result: The.100.S04E01................... with 755 seeders and 4 leechers
13:51:35 DEBUG::SEARCHQUEUE-MANUAL-268592 :: [T411] :: Found result: The.100.S04E01................... with 467 seeders and 1 leechers
```

**Comment by turak** [comment] 2017-03-03 22:11
server restarted, always the same error.. i don't know why..
all upgrade.

**Comment by miigotu** [comment] 2017-03-03 22:20
What is the locale on the server?

**Comment by turak** [comment] 2017-03-03 22:28
```
➜  Logs git:(develop) locale 
LANG=fr_FR.UTF-8
LANGUAGE=fr_FR:fr
LC_CTYPE=fr_FR.UTF-8
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=

```

**Comment by turak** [comment] 2017-03-04 17:28
or linked to python version ?

**Closed** 2017-03-05 05:23 UTC

**Comment by gormson** [comment] 2017-03-05 16:15
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.7**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@100c4a192532262ac7333b4bb1d86501ddd3446c
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [T411] :: [100c4a1] Request failed: data must be a byte string
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Cerafin** [comment] 2017-03-06 11:35
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.7**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5071e52c498fc145838231f4fb85565fa6ffa70b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-153021 :: [T411] :: [5071e52] Request failed: data must be a byte string
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment] 2017-03-06 12:35
Try updating python to 2.7.10-2.7.12

**Comment by turak** [comment] 2017-03-06 13:14
```
➜  .sickrage git:(develop) /usr/bin/env python2.7 -V
Python 2.7.13
```
And always same error.. I don't understand :/

Server completly reinstall..
Only the problem with T411 providers :/

**Comment by turak** [comment] 2017-03-06 15:17
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-8**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@a178fa4136225bbf3144927c06f9ee8a7d2aae3a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-311819 :: [T411] :: [a178fa4] Request failed: data must be a byte string
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Cerafin** [comment] 2017-03-06 15:51
I changed the path of the python's command into this file : /etc/systemd/system/sickrage.service
After a restart I can see in sickrage that python 2.7.12 in now used : 2.7.12 (default, Mar 6 2017, 16:36:33) [GCC 4.9.2]
And it works fine now. 
Thanks @miigotu

**Comment by turak** [comment] 2017-03-06 16:30
thanks @Cerafin in  i confirm that.
Path change to

/usr/loca/bin/python2.7

so it's fixed

**Comment by bibi32** [comment] 2017-03-07 11:25
### INFO
Python Version: **2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]**
Operating System: **Linux-4.4.40-1-pve-x86_64-with-debian-8.7**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5071e52c498fc145838231f4fb85565fa6ffa70b
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [T411] :: [5071e52] Request failed: data must be a byte string
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by miigotu** [comment] 2017-03-24 12:44
If anyone is still having this issue, please update and try again. If it is still an issue after update, please give me the log of about 5 lines before and after the error.
