### ISSUE TITLE
utorrent labels not working properly

### ISSUE THREAD

**Issue by syrys** [SickRage/SickRage#1578] opened 2016-04-19 21:26 UTC
Hey guys,

This happened about a month ago. I have setup my SR to download using uTorrent. I have a downloads folder, and within in a sickrage folder. I have told SR to put a label "sickrage" to all the utorrent downloads. And i have told uTorrent to put downloads into subfolders matching the label. Obviously the post processor is linked to the sickrage folder.

these settings were working perfectly for the last 6 months or so. But all of a sudden few weeks ago, i am seeing some new shows i added get downloaded directly into the downloads folder instead of the sickrage subfolder. Im not really sure why.

So, i looked at the said downloaded shows on uTorrent to check if the label exists, and indeed they do. but they are not downloaded into the the sickrage folder. lot of my shows are actually being downloaded to the sickrage folder, but some arnt (specially the recently added ones). From a quick glance, they all seem to be adding the correct label to uTorrent, but i cant really tell if they added it with some hidden characters/whitespace etc.

Where is the problem coming from? SR? or uTorrent?

Branch: master
Commit: 5709abdbe82611c8c941ddc0cda9784e8ef65bcd
OS: Windows 10

**Comment by SickRage2** [comment] 2016-04-19 21:26
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment] 2016-04-20 04:10
made sure the labels are lowercase?  Pretty sure it isnt a SR issue.

**Comment by syrys** [comment] 2016-04-20 09:06
yeah made sure that they are all lower case. what i cant make sure is if SR is accidentally appending whitespace etc to the label (not sure how to test for that). puzzling thing is, it worked perfectly few weeks back. And even now, 75% of my shows work just fine, but the other 25% doesnt get put in the correct folder (its not limited to either shows or anime, happen to both though mostly anime, but i have added a lot of anime to my library recently, so maybe it has something to do with that?). I have set SR to auto update, but my uTorrent doesnt, so the only thing that changed between not having the problem and having it, is SR updates.

Its fine, if you guys are completely sure that it has nothing to do with recent SR changes, im happy to try re-install uTorrent and/or try a different client (qbittorrent) and see if they make any difference, when i get some free time that is :)

**Comment by miigotu** [comment] 2016-04-25 12:14
btw, are you sure the ones in the download folder are not just the ones that are incomplete?  Anyways, closing this.

**Closed by miigotu** 2016-04-25 12:14 UTC
Labels: Question

**Comment by syrys** [comment] 2016-04-25 21:06
@miigotu yup, im sure. i have a separate incomplete folder in the same drive which works fine. And my client shows the said files to have finished downloading.

**Comment by miigotu** [comment] 2016-04-25 23:45
Maybe that will help, dunno if it will fix anything or not.

**Comment by syrys** [comment] 2016-04-26 00:30
@miigotu 
Awesome, i will report back in few days :D

**Comment by vapervapes** [comment] 2016-04-28 19:43
@syrys 

I had the same issue check if you had uTorrent on auto update this is a bug with the latest version i just re-installed an older version of uTorrent and is working like a charm

**Comment by sagilo** [comment] 2016-12-06 18:40
@vapervapes can you please write the last confirmed version it works on?
