### ISSUE TITLE
Add Provider Nyaa.si

### ISSUE THREAD

**Issue by Nibeck1309** [SickRage/SickRage#3771] opened 2017-05-19 15:58 UTC
Hello,

Can you add Anime Provider https://nyaa.si for Nyaa replacement

Flux rss : https://nyaa.si/?page=rss&c=1_0&f=0

thks

**Comment by h3llrais3r** [comment] 2017-05-19 16:00
Duplicate of https://github.com/SickRage/SickRage/issues/3753

**Closed by h3llrais3r** 2017-05-19 16:00 UTC
