### ISSUE TITLE
Adding yggtorrent to new torrent provider ?

### ISSUE THREAD

**Issue by Pitizila** [SickRage/SickRage#3934] opened 2017-07-17 10:42 UTC
hi, is there any way to add yggtorent(dot)com to search providers ? Since t411 is definitely down, it would be useful :)

**Comment by sharkykh** [comment] 2017-07-17 19:53
Duplicate of #3915 
I'll get to it when I get a chance.

**Closed by sharkykh** 2017-07-17 19:53 UTC
Labels: Duplicate
