### ISSUE TITLE
Error: no such column: tv_eps.showid

### ISSUE THREAD

**Issue by baronebirra82** [SickRage/SickRage#3249] opened 2017-02-28 16:30 UTC
SickRage Info:
Branch: master
Commit: ad926e47cafd7bb9b919acc0e038f56cc7aa9aa5
Version: v2017.02.28-1
Database Version: 44.0
Python Version: 2.7.10 (default, Jul 8 2015, 08:04:18) [GCC 4.3.6]
SSL Version: OpenSSL 1.0.1o 12 Jun 2015
OS: Linux-3.12.6-x86_64-with-glibc2.0
Locale: en_US.UTF-8

When i try to reach the tv shows home page i get this error (link to the log error page that works):
2017-02-28 17:28:18 Thread-14 :: [ad926e4] DB error: no such column: tv_eps.showid
2017-02-28 17:28:18 Thread-14 :: [ad926e4] Failed doing webui callback: Traceback (most recent call last):
File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 279, in async_call
result = function(**kwargs)
File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 728, in index
stats = self.show_statistics()
File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 754, in show_statistics
sql_result = main_db_con.select(sql_statement)
File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/db.py", line 292, in select
sql_results = self.action(query, args, fetchall=True)
File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/db.py", line 262, in action
sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/db.py", line 111, in _execute
sql_results = self.connection.cursor().execute(query)
OperationalError: no such column: tv_eps.showid

2017-02-28 17:24:14 Thread-15 :: [ad926e4] DB error: no such column: tv_eps.showid
2017-02-28 17:24:14 Thread-15 :: [ad926e4] Failed doing webui callback: Traceback (most recent call last):
File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 279, in async_call
result = function(**kwargs)
File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 728, in index
stats = self.show_statistics()
File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 754, in show_statistics
sql_result = main_db_con.select(sql_statement)
File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/db.py", line 292, in select
sql_results = self.action(query, args, fetchall=True)
File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/db.py", line 262, in action
sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/db.py", line 111, in _execute
sql_results = self.connection.cursor().execute(query)
OperationalError: no such column: tv_eps.showid

**Comment by SickRage2** [comment] 2017-02-28 16:30
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sharkykh** [comment] 2017-02-28 17:43
@baronebirra82 ,
I made a fix for this and I need you to test it.
Do you know how to add a git remote?

**Comment by tapessur** [comment] 2017-02-28 18:50
@sharkykh Ran into same issue. Switched to develop branch and can confirm the fix seems to be working; with the following error and warning, which based on your code is the expected result:

2017-02-28 19:47:58 Thread-14 :: [2d666e8] DB error: no such column: tv_eps.showid
2017-02-28 19:47:58 Thread-14 :: Database selection failed. Using fallback select statement.

**Comment by sharkykh** [comment] 2017-02-28 19:00
@tapessur 
First of all thank you.
And yeah it's working, but that's not a fix...
I reverted the code back to what it was before a change I made to fix some other non-critical issue.

I can't seem to reproduce this on my machine. Are you running QSickRage too?

**Comment by tapessur** [comment] 2017-02-28 19:02
Ah, I see... Yep, running QSickRage as well...
thanks!

**Comment by miigotu** [comment] 2017-02-28 19:04
Simpler SQL! =p

**Comment by sharkykh** [comment] 2017-02-28 19:07
@miigotu Simpler was the DISTINCT method. But you said then that it didn't work for some.

**Comment by miigotu** [comment] 2017-02-28 19:11
I don't remember bwaha

**Comment by miigotu** [comment] 2017-02-28 19:22
I think its the sqlite3.Row bs, there is another issue about e.season now

**Comment by sharkykh** [comment] 2017-02-28 19:26
Nope. That's another error I've made. :(

**Closed** 2017-03-01 02:38 UTC
Labels: Bug / Issue, Fixed
