### ISSUE TITLE
Double url-encoding in search terms causing no results (possibly only for Torrentday provider)

### ISSUE THREAD

**Issue by AubreyKilian** [SickRage/SickRage#3365] opened 2017-03-09 08:34 UTC
### Before submitting your issue:

Branch/Commit: master/edc61acc6934ac3e15568ed07c37b06233ec19a9
OS: Ubuntu 16.04.2 LTS
What you did: Added "Pokémon" as a show with future and current episode status as "Skipped".  Allowed show to update and refresh.  Clicked the "Search" button next to an episode's name in the show.  (Current only search provider is Torrentday - I'm unsure if this problem may exist with other providers)
What happened: Sickrage correctly started a search for the episode, but did not found the episode in question, even though the episode is definitely there.
What you expected: Episode found, and snatched.
Logs:
```
2017-03-09 09:27:04 DEBUG    SEARCHQUEUE-MANUAL-76703 :: [TorrentDay] :: Search Mode: Episode
2017-03-09 09:27:04 DEBUG    SEARCHQUEUE-MANUAL-76703 :: [TorrentDay] :: Search string: Pokémon S20E17
2017-03-09 09:27:05 DEBUG    SEARCHQUEUE-MANUAL-76703 :: [TorrentDay] :: POST URL: https://classic.torrentday.com/V3/API/API.php [Status: 200]
2017-03-09 09:27:05 DEBUG    SEARCHQUEUE-MANUAL-76703 :: [TorrentDay] :: With post data: cata=yes&search=Pok%C3%A9mon+S20E17&c26=1&jxt=8&jxw=b&c24=1&c2=1&c34=1&c7=1
2017-03-09 09:27:05 DEBUG    SEARCHQUEUE-MANUAL-76703 :: [TorrentDay] :: Data returned from provider does not contain any torrents
2017-03-09 09:27:05 DEBUG    SEARCHQUEUE-MANUAL-76703 :: [TorrentDay] :: Search string: Sun &amp; Moon S20E17
2017-03-09 09:27:05 DEBUG    SEARCHQUEUE-MANUAL-76703 :: [TorrentDay] :: POST URL: https://classic.torrentday.com/V3/API/API.php [Status: 200]
2017-03-09 09:27:05 DEBUG    SEARCHQUEUE-MANUAL-76703 :: [TorrentDay] :: With post data: cata=yes&search=Sun+%26amp%3B+Moon+S20E17&c26=1&jxt=8&jxw=b&c24=1&c2=1&c34=1&c7=1
2017-03-09 09:27:05 DEBUG    SEARCHQUEUE-MANUAL-76703 :: [TorrentDay] :: Data returned from provider does not contain any torrents
2017-03-09 09:27:05 DEBUG    SEARCHQUEUE-MANUAL-76703 :: [TorrentDay] :: Fallback season pack search initiate
2017-03-09 09:27:05 INFO     SEARCHQUEUE-MANUAL-76703 :: [TorrentDay] :: Performing season pack search for Pokémon
```

Some notes:
1) Using CURL to simulate the searches yielded positive results, only when fixing double encoding (I manually stuck my cookies into the cookies file):

curl -c ./cookies -b ./cookies -d 'cata=yes&search=Sun+%26+Moon+S20E01&c26=1&jxt=8&jxw=b&c29=1&c24=1&c2=1&c34=1&c7=1' https://classic.torrentday.com/V3/API/API.php

(Notice the search term is fixed from %26amp%3B to just %26)
The above curl command returns an actual JSON result with the episode in.

2) Torrentday's uploaders are uploading the episodes with "Pokemon" instead of "Pokémon" in the description, which influences the search.

Things I've tried:
1) Added "Pokemon" as scene exception in show settings - didn't help.
2) Added "c29" as a category to the Torrentday.py script (c29 = Anime category, and Pokemon appears in c29), this helped me find the episodes on the curl command line, but sickrage still didn't find them.
**3) Unescaping the %26amp%3B to be only %26 in the search string does fix the problem.**

**Comment by SickRage2** [comment] 2017-03-09 08:34
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by NickMolloy** [comment] 2017-03-09 11:54
I am able to reproduce this with other search providers. However, it is not SickRage that is doing that encoding, that is how it is provided from xem:
```
"76703": ["Indigo League", "Adventures on the Orange Islands", "The Johto Journeys", "Johto League Champions", "Master Quest", "Advanced", "Advanced Challenge", "Advanced Battle", "Battle Frontier", "Diamond and Pearl", "Diamond and Pearl: Battle Dimension", "Diamond and Pearl: Galactic Battles", "Diamond and Pearl: Sinnoh League Victors", "Black & White", "Black & White: Rival Destinies", "Black & White: Adventures in Unova", "XY", "XY: Kalos Quest", "XY&Z", "Sun &amp; Moon"]
```

For some reason, "XY&Z" isn't encoded, but "Sun &amp; Moon" is.

**Comment by AubreyKilian** [comment] 2017-03-09 11:59
Hmm, good point, I did not think to determine the source of the encoding...

**Comment by miigotu** [comment] 2017-03-09 18:00
I asked the #xem channel on freenode to fix this for you.

**Comment by AubreyKilian** [comment] 2017-03-09 18:45
Ah that's awesome, thank you.

**Comment by AubreyKilian** [comment] 2017-03-09 18:45
Ah that's awesome, thank you.

**Comment by AubreyKilian** [comment] 2017-03-09 18:45
Ah that's awesome, thank you.

**Comment by miigotu** [comment] 2017-03-09 18:58
Until then, you can check view-source:http://thexem.de/xem/show/3641 and look for `<span class="name" data-id="5166">Sun &amp; Moon</span>` When it starts working or is changed to `<span class="name" data-id="5166">Sun & Moon</span>` you can close this

Waiting for http://thexem.de/xem/draft/3641 to be approved

**Comment by sharkykh** [comment] 2017-03-09 19:03
@miigotu  @AubreyKilian 
Or http://thexem.de/map/allNames?origin=tvdb&season=20&id=76703

**Comment by sharkykh** [comment] 2017-03-09 19:13
Changed

**Comment by miigotu** [comment] 2017-03-09 19:13
Force an update of the show to make sure you get the new data.

**Closed by sharkykh** 2017-03-09 19:13 UTC
Labels: In progress, Upstream
