### ISSUE TITLE
Force backlog search

### ISSUE THREAD

**Issue by W13N3N** [SickRage/SickRage#1675] opened 2016-05-02 12:20 UTC
I've recently switched from Sickbeard to Sickrage and i'm rely exited how well everything looks and works so first of all, thumbs up to all devs!!!

I only got one slight problem i can't resolve;

My Homeserver automatically turns on at 6pm (because mostly i don't need to use it during the day) and automatically shuts down at 2am to save some money on electric costs.

Only the backlog search can't be set les then 12 hours. So every time my homeserver boots Sickrage sets it's backlog search to run 12 hours later. Because my Homeserver is already shut down before the 12 hours are passed my backlog search will never run.

Is there a way to force it automatically? Maybe on boot?

Hopefully someone can help me out.

**Comment by SickRage2** [comment] 2016-05-02 12:20
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by p0psicles** [comment] 2016-05-02 12:47
you can cron (schedule) the force backlog request. You'll have to use basic authentication, as the REST api doesn't provide that service. So in short, open chrome dev tools, open the network tab. Go to the "manage searches" page. Start the backlog, and check the request.

Then add your password/username to it. Like http://username:password@my.sickrage.server/sickrage/manage/manageSearches/forceBacklog.

And schedule that through a curl or wget, at server startup.

You could of course start a feature request, to get the forceBacklog added to the rest api. That would be a little cleaner.

**Comment by OmgImAlexis** [comment] 2016-05-02 12:53
I'm marking this as "won't fix" since this isn't the way Sickrage was made to be used.

**Closed by OmgImAlexis** 2016-05-02 12:53 UTC
Labels: Wontfix

**Comment by p0psicles** [comment] 2016-05-02 13:49
@W13N3N, well @OmgImAlexis is right, as this is not a SickRage issue, and it's not possible to start backlog at startup by design.

Like i've shown you, there are ways around it. If you need additional help on it, i suggest you give us a visit on IRC.
