### ISSUE TITLE
'Add From IMDB's Popular Shows' Error

### ISSUE THREAD

**Issue by DazzFX** [SickRage/SickRage#2141] opened 2016-07-26 13:47 UTC
Branch: master
Commit: 570cd207fe00798fb2182b0a90af16c1d936ea83
Version: 2016.07.10-1
Database Version: 44.0
OS: Windows 10

When going into 'Add From IMDB's Popular Shows', I'm getting an error that says:

Fetching of IMDB Data failed. Are you online? Exception:
'NoneType' object is not callable

Adding from Trakt Lists seems to work okay.  Maybe something has changed w/IMDB?

**Comment by SickRage2** [comment] 2016-07-26 13:47
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment] 2016-07-26 15:40
Indeed, seems they changed something on the IMDB side.
Thanks for the report.

**Comment by sm-k** [comment] 2016-07-27 05:32
looks like the whole structure of the page changed from using tables to divs lol

**Comment by sm-k** [comment] 2016-07-27 05:48
notes - 

    main container: .lister-item
    iterate .lister-item
        image: .lister-item-image img attribute=src
        tt: .lister-item-image img attribute=tconst
        title: .lister-item-header a
        url: .lister-item-header a attribute=href
        rating: .rating.rating-list meta itemprop=ratingValue attribute=content
        ratingCount: .rating.rating-list meta itemprop=ratingCount attribute=content
        
        
        

i'll fix this tomorrow when i get off work if it's not done by then

**Comment by sm-k** [comment] 2016-07-28 07:28
@neoatomic  i have this fixed here - https://github.com/sm-k/SickRage/commit/6fdda8e21abae37fe1a502f11af7551df83e2722

however there seems to be an issue when you actually click 'add show'? everything in the link looks fine, it successfully gets the id from tvdb and so on, but then this error gets thrown:

    2016-07-28 00:07:56 DEBUG    SHOWQUEUE-REMOVE-SHOW :: No shows found in your library, aborting library update
    2016-07-28 00:07:56 DEBUG    SHOWQUEUE-REMOVE-SHOW :: Trakt may have some issues and it's unavailable. Try again later please
    2016-07-28 00:07:55 DEBUG    SHOWQUEUE-REMOVE-SHOW :: Transaction with 5 queries executed
    2016-07-28 00:07:55 INFO     SHOWQUEUE-REMOVE-SHOW :: Removing Animal Kingdom (2016)
    AA
    AATypeError: 'int' object is not iterable
    AA    for value in values:
    AA  File "c:\users\User\desktop\sickrage\sickbeard\blackandwhitelist.py", line 53, in _add_keywords
    AA    self._add_keywords(b'whitelist', values)
    AA  File "c:\users\User\desktop\sickrage\sickbeard\blackandwhitelist.py", line 74, in set_white_keywords
    AA    self.show.release_groups.set_white_keywords(self.whitelist)
    AA  File "c:\users\User\desktop\sickrage\sickbeard\show_queue.py", line 403, in run
    2016-07-28 00:07:51 DEBUG    SHOWQUEUE-ADD :: Traceback (most recent call last):
    AATypeError: 'int' object is not iterable
    AA    for value in values:
    AA  File "c:\users\User\desktop\sickrage\sickbeard\blackandwhitelist.py", line 53, in _add_keywords
    AA    self._add_keywords(b'whitelist', values)
    AA  File "c:\users\User\desktop\sickrage\sickbeard\blackandwhitelist.py", line 74, in set_white_keywords
    AA    self.show.release_groups.set_white_keywords(self.whitelist)
    AA  File "c:\users\User\desktop\sickrage\sickbeard\show_queue.py", line 403, in run
    AATraceback (most recent call last):
    2016-07-28 00:07:51 ERROR    SHOWQUEUE-ADD :: [570cd20] Error trying to add show: 'int' object is not iterable
    2016-07-28 00:07:51 DEBUG    SHOWQUEUE-ADD :: Building black and white list for 304262
    2016-07-28 00:07:51 INFO     SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
    2016-07-28 00:07:51 DEBUG    SHOWQUEUE-ADD :: Setter sets location to O:\TV Shows\Animal Kingdom (2016)
    2016-07-28 00:07:51 DEBUG    SHOWQUEUE-ADD :: 304262: Loading show info from theTVDB
    2016-07-28 00:07:51 INFO     SHOWQUEUE-ADD :: 304262: Unable to find the show in the database
    2016-07-28 00:07:50 INFO     SHOWQUEUE-ADD :: theTVDB: {'useZip': True, 'apikey': '~', 'cache': u'c:\\users\\User\\desktop\\sickrage\\cache\\indexers\\theTVDB', 'language': u'en'}
    2016-07-28 00:07:50 INFO     SHOWQUEUE-ADD :: theTVDB: {'useZip': True, 'apikey': '~', 'cache': u'c:\\users\\User\\desktop\\sickrage\\cache\\indexers\\theTVDB', 'language': u'en'}
    2016-07-28 00:07:50 INFO     SHOWQUEUE-ADD :: Starting to add show by Indexer Id: 304262

trakt is currently offline for database maintenance but it seems bizarre that there would be that dependence on it?

**Comment by neoatomic** [comment] 2016-07-28 08:49
@sm-k Good work. :) 
Maybe @p0psicles is able to tell what go's wrong here.

**Comment by neoatomic** [comment] 2016-08-05 09:24
@sm-k This might help you finding the issue. 
https://github.com/pymedusa/SickRage/commit/434cb96e67f6bf2f98482baa471376630c4129d5

**Comment by sm-k** [comment] 2016-08-06 01:13
@neoatomic it doesn't look like the issue is even related to the imdb code after fixing that - any show you add through  https://github.com/SickRage/SickRage/blob/4e8b9eeb3157adb5fcdee67ef68610c0bb65abf4/sickbeard/webserve.py#L2656 gets set as anime and so it tries to process the whitelist/blacklist when it doesn't exist.

**Comment by FatRat34** [comment] 2016-08-08 18:47
Also have this error

SickRage Info:
Branch: master
Commit: 4e8b9eeb3157adb5fcdee67ef68610c0bb65abf4
Version: 2016.07.31-1
Database Version: 44.0
  Python Version: 2.7.3 (default, Jun 21 2016, 18:38:19) [GCC 4.7.2]
  SSL Version: OpenSSL 1.0.1e 11 Feb 2013
  OS: Linux-3.2.0-4-amd64-x86_64-with-debian-7.11
  Locale: None.None

**Comment by ezar** [comment] 2016-08-16 13:29
Same here!

> Fetching of IMDB Data failed. Are you online? Exception:
> 'NoneType' object is not callable
>

**Comment by ddonindia** [comment] 2016-08-20 13:13
Same here!

**Comment by xmenxmen** [comment] 2016-08-25 11:17
Same here

**Comment by CDeLeon94** [comment] 2016-09-01 03:03
Any debugging I can do on my end at the superuser level? Not a programmer, but I understand logs and code more than the average user. I'd like to get this fixed, but its not a huge deal.

**Comment by sharkykh** [comment] 2017-02-27 21:27
I believe it was fixed by #2257. Closing

**Closed by sharkykh** 2017-02-27 21:27 UTC
Labels: Bug / Issue, Confirmed
